# Generated by Django 5.2.17 on 2026-09-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_search_trigram"),
        ("ingestion", "0002_alter_dataqualityissue_source_system_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("mail", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("visibility", models.CharField(blank=True, max_length=16)),
                ("site_path", models.CharField(blank=True, max_length=255)),
                ("tenant_domain", models.CharField(blank=True, max_length=128)),
                ("group_created", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlannerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_id", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, max_length=64)),
                ("plan_created", models.DateTimeField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=128)),
                ("category_descriptions", models.JSONField(blank=True, default=dict)),
                (
                    "board_kind",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow board"),
                            ("job", "Per-job plan"),
                            ("punch", "Punch list"),
                            ("admin", "Team & admin"),
                        ],
                        default="admin",
                        max_length=12,
                    ),
                ),
                (
                    "board_kind_auto",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow board"),
                            ("job", "Per-job plan"),
                            ("punch", "Punch list"),
                            ("admin", "Team & admin"),
                        ],
                        default="admin",
                        max_length=12,
                    ),
                ),
                ("board_kind_manual", models.BooleanField(default=False)),
                ("av_stage", models.CharField(blank=True, max_length=24)),
                ("task_count", models.IntegerField(default=0)),
                ("open_count", models.IntegerField(default=0)),
                ("overdue_count", models.IntegerField(default=0)),
                ("last_change", models.DateTimeField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="planner.plannergroup",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["group__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="PlannerBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bucket_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("order_hint", models.CharField(blank=True, max_length=64)),
                ("etag", models.CharField(blank=True, max_length=128)),
                ("active", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="planner.plannerplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "order_hint"],
            },
        ),
        migrations.CreateModel(
            name="PlannerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=512)),
                ("percent", models.SmallIntegerField(default=0)),
                ("priority", models.SmallIntegerField(default=5)),
                ("start", models.DateField(blank=True, null=True)),
                ("due", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("task_created", models.DateTimeField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=128)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("label_keys", models.JSONField(blank=True, default=list)),
                ("assignee_ids", models.JSONField(blank=True, default=list)),
                ("assignee_names", models.JSONField(blank=True, default=list)),
                ("checklist_done", models.SmallIntegerField(default=0)),
                ("checklist_total", models.SmallIntegerField(default=0)),
                ("has_description", models.BooleanField(default=False)),
                ("reference_count", models.SmallIntegerField(default=0)),
                ("order_hint", models.CharField(blank=True, max_length=64)),
                ("created_by_id", models.CharField(blank=True, max_length=64)),
                ("completed_by_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("checklist", models.JSONField(blank=True, default=list)),
                ("references", models.JSONField(blank=True, default=list)),
                ("details_etag", models.CharField(blank=True, max_length=128)),
                ("details_pending", models.BooleanField(default=False)),
                ("project_rule", models.CharField(blank=True, max_length=32)),
                ("quote_ref", models.CharField(blank=True, max_length=12)),
                ("last_change", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="planner.plannerbucket",
                    ),
                ),
                (
                    "first_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="planner.plannerplan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planner_tasks",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "bucket_id", "order_hint"],
            },
        ),
        migrations.CreateModel(
            name="PlannerTaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(db_index=True)),
                ("field", models.CharField(max_length=24)),
                ("old", models.TextField(blank=True)),
                ("new", models.TextField(blank=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="planner.plannertask",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlannerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("mail", models.CharField(blank=True, max_length=255)),
                ("upn", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("account_enabled", models.BooleanField(default=True)),
                ("employee_rule", models.CharField(blank=True, max_length=32)),
                ("employee_confidence", models.FloatField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planner_users",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddIndex(
            model_name="plannertask",
            index=models.Index(
                fields=["project", "active"], name="planner_pla_project_bd3394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannertask",
            index=models.Index(
                fields=["plan", "active"], name="planner_pla_plan_id_77bf04_idx"
            ),
        ),
    ]
