# Generated by Django 5.2.17 on 2026-08-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_employee_is_field_hourly"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlCnetOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_nbr", models.CharField(max_length=12, unique=True)),
                ("cnet_number", models.CharField(db_index=True, max_length=16)),
                ("so_type", models.CharField(db_index=True, max_length=6)),
                ("cust_id", models.CharField(blank=True, db_index=True, max_length=15)),
                ("slsper_id", models.CharField(blank=True, max_length=10)),
                ("ord_date", models.DateField(db_index=True, null=True)),
                ("status", models.CharField(blank=True, max_length=4)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "tot_ord",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_merch",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_frt",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_tax",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                ("cust_ord_nbr", models.CharField(blank=True, max_length=48)),
                ("ship_name", models.CharField(blank=True, max_length=120)),
                ("ship_city", models.CharField(blank=True, max_length=64)),
                ("ship_state", models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="SlCnetShipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipper_id", models.CharField(max_length=12, unique=True)),
                ("ord_nbr", models.CharField(db_index=True, max_length=12)),
                ("ship_date", models.DateField(null=True)),
                (
                    "invc_nbr",
                    models.CharField(blank=True, db_index=True, max_length=12),
                ),
                ("invc_date", models.DateField(null=True)),
                ("status", models.CharField(blank=True, max_length=4)),
                (
                    "tot_invc",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_cost",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_frt",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_merch",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CnetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_id", models.IntegerField(unique=True)),
                ("document_number", models.CharField(db_index=True, max_length=16)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("quote", "Quote"), ("sales_order", "Sales Order")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("revision", models.IntegerField(default=1)),
                ("status", models.CharField(blank=True, db_index=True, max_length=24)),
                ("stage", models.CharField(blank=True, max_length=32)),
                (
                    "probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(db_index=True, null=True)),
                ("created_by_name", models.CharField(blank=True, max_length=80)),
                ("created_by_email", models.CharField(blank=True, max_length=120)),
                (
                    "ordered_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ordered_by_name", models.CharField(blank=True, max_length=80)),
                ("ordered_by_email", models.CharField(blank=True, max_length=120)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_sl_id",
                    models.CharField(blank=True, db_index=True, max_length=15),
                ),
                ("customer_company", models.CharField(blank=True, max_length=120)),
                ("tax_status", models.CharField(blank=True, max_length=24)),
                ("terms", models.CharField(blank=True, max_length=48)),
                ("price_profile", models.CharField(blank=True, max_length=48)),
                (
                    "salesperson_name",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("salesperson_email", models.CharField(blank=True, max_length=120)),
                ("account_manager_name", models.CharField(blank=True, max_length=80)),
                ("account_manager_email", models.CharField(blank=True, max_length=120)),
                ("customer_po", models.CharField(blank=True, max_length=48)),
                ("ship_company", models.CharField(blank=True, max_length=120)),
                ("ship_attn", models.CharField(blank=True, max_length=80)),
                ("ship_city", models.CharField(blank=True, max_length=64)),
                ("ship_state", models.CharField(blank=True, max_length=8)),
                ("ship_zip", models.CharField(blank=True, max_length=16)),
                ("ship_addr1", models.CharField(blank=True, max_length=120)),
                ("bill_city", models.CharField(blank=True, max_length=64)),
                ("note_internal", models.TextField(blank=True)),
                ("note_external", models.TextField(blank=True)),
                ("note_shipping", models.TextField(blank=True)),
                (
                    "total_item_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "shipping_handling",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "misc_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("line_count", models.IntegerField(default=0)),
                (
                    "sl_ord_nbr",
                    models.CharField(blank=True, db_index=True, max_length=12),
                ),
                (
                    "sl_so_type",
                    models.CharField(blank=True, db_index=True, max_length=6),
                ),
                ("sl_status", models.CharField(blank=True, max_length=4)),
                ("sl_cancelled", models.BooleanField(default=False)),
                ("sl_ord_date", models.DateField(blank=True, null=True)),
                (
                    "realized_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "realized_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "realized_freight_charged",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                ("first_ship_date", models.DateField(blank=True, null=True)),
                ("last_ship_date", models.DateField(blank=True, null=True)),
                ("fully_shipped", models.BooleanField(default=False)),
                ("conversion_method", models.CharField(blank=True, max_length=24)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "converted_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quotes",
                        to="sales.cnetdocument",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cnet_documents",
                        to="core.customer",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CnetDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_item_id", models.BigIntegerField()),
                ("line_number", models.IntegerField(default=0)),
                ("line_order", models.IntegerField(default=0)),
                ("product_type", models.CharField(blank=True, max_length=24)),
                ("status", models.CharField(blank=True, max_length=24)),
                (
                    "manufacturer",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("manufacturer_id", models.CharField(blank=True, max_length=16)),
                (
                    "part_number",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("sub_category", models.CharField(blank=True, max_length=64)),
                ("upc", models.CharField(blank=True, max_length=32)),
                ("dropship", models.BooleanField(default=False)),
                ("taxable", models.BooleanField(default=False)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "qty_cancelled",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "ext_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ext_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "supplier_name",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("supplier_account", models.CharField(blank=True, max_length=32)),
                ("supplier_sku", models.CharField(blank=True, max_length=48)),
                (
                    "sl_line_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("sl_line_matched", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.cnetdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CnetLineSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(db_index=True, max_length=80)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serials",
                        to="sales.cnetdocumentline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gl010Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=4)),
                ("period", models.IntegerField()),
                ("sub", models.CharField(db_index=True, max_length=8)),
                ("acct", models.CharField(max_length=10)),
                ("acct_class", models.CharField(db_index=True, max_length=16)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
            ],
            options={
                "unique_together": {("fiscal_year", "period", "sub", "acct")},
            },
        ),
        migrations.CreateModel(
            name="SlCnetOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_nbr", models.CharField(db_index=True, max_length=12)),
                ("line_ref", models.CharField(max_length=8)),
                ("invt_id", models.CharField(blank=True, db_index=True, max_length=40)),
                ("descr", models.CharField(blank=True, max_length=80)),
                (
                    "qty_ord",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "qty_ship",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "qty_bo",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_cost",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "sls_price",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_ord",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
            ],
            options={
                "unique_together": {("ord_nbr", "line_ref")},
            },
        ),
        migrations.AddIndex(
            model_name="cnetdocument",
            index=models.Index(
                fields=["doc_type", "status"], name="sales_cnetd_doc_typ_da0be5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cnetdocument",
            index=models.Index(
                fields=["doc_type", "ordered_at"], name="sales_cnetd_doc_typ_277b5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cnetdocument",
            index=models.Index(
                fields=["salesperson_name", "doc_type"],
                name="sales_cnetd_salespe_6a4eeb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cnetdocumentline",
            index=models.Index(
                fields=["part_number"], name="sales_cnetd_part_nu_7730fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cnetdocumentline",
            index=models.Index(
                fields=["manufacturer"], name="sales_cnetd_manufac_bba3ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cnetdocumentline",
            unique_together={("document", "line_item_id")},
        ),
        migrations.AlterUniqueTogether(
            name="cnetlineserial",
            unique_together={("line", "serial")},
        ),
    ]
