# Generated by Django 5.2.17 on 2026-08-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slcnetorder",
            name="cnet_number",
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
