# Generated by Django 5.2.17 on 2026-09-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_widen_cnet_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlCnetShipperSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipper_id", models.CharField(db_index=True, max_length=12)),
                ("line_ref", models.CharField(max_length=8)),
                ("ord_nbr", models.CharField(db_index=True, max_length=12)),
                ("invt_id", models.CharField(blank=True, max_length=40)),
                ("serial", models.CharField(db_index=True, max_length=80)),
                (
                    "qty_ship",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                ("rma_disposition", models.CharField(blank=True, max_length=16)),
                ("sl_created_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlCnetShipperLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipper_id", models.CharField(db_index=True, max_length=12)),
                ("line_ref", models.CharField(max_length=8)),
                ("ord_nbr", models.CharField(db_index=True, max_length=12)),
                ("ord_line_ref", models.CharField(blank=True, max_length=8)),
                ("invt_id", models.CharField(blank=True, db_index=True, max_length=40)),
                ("descr", models.CharField(blank=True, max_length=80)),
                (
                    "qty_ship",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "sls_price",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_cost",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_invc",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tot_merch",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                ("site_id", models.CharField(blank=True, max_length=10)),
                ("sl_created_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipper_id", "line_ref"), name="uniq_sl_shipper_line"
                    )
                ],
            },
        ),
    ]
