# Generated by Django 5.2.17 on 2026-09-10 17:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("bids", "0002_bidclientalias_candidates"),
        ("core", "0007_search_trigram"),
    ]

    operations = [
        migrations.CreateModel(
            name="HygieneReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
                ("trigger", models.CharField(blank=True, max_length=24)),
                ("counts", models.JSONField(default=dict)),
                ("notes", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-ran_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "Share folder file"),
                            ("bootstrap", "Dashboard bootstrap"),
                            ("upload", "Uploaded in PCA"),
                        ],
                        default="file",
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=500)),
                ("date_key", models.IntegerField(default=0)),
                ("date_label", models.CharField(blank=True, max_length=32)),
                ("date_precision", models.CharField(blank=True, max_length=8)),
                ("rows", models.IntegerField(default=0)),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                ("file_mtime", models.FloatField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mode", models.CharField(blank=True, max_length=12)),
                ("counts", models.JSONField(blank=True, default=dict)),
                (
                    "loaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_key", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(db_index=True, max_length=120)),
                ("manufacturer_raw", models.CharField(blank=True, max_length=200)),
                ("part", models.CharField(max_length=160)),
                ("part_norm", models.CharField(db_index=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "msrp",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "map_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255)),
                ("date_key", models.IntegerField(default=0)),
                ("confidence", models.SmallIntegerField(default=0)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                (
                    "archive_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "current"),
                            ("duplicate", "duplicate part (better row kept)"),
                            ("version", "older version of the same family"),
                            ("pre2023", "priced before 2023"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="estimating.catalogitem",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="estimating.catalogsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "equipment_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "equipment_sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "labor_sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "labor_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("line_count", models.IntegerField(default=0)),
                ("room_count", models.IntegerField(default=0)),
                ("version_no", models.IntegerField(default=0)),
                ("approval_ref", models.CharField(blank=True, max_length=64)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="bids.bid",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="core.customer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="access.account",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.IntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("totals", models.JSONField(default=dict)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="estimating.estimate",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_no"],
            },
        ),
        migrations.CreateModel(
            name="LaborRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_id", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=60)),
                (
                    "group",
                    models.CharField(
                        choices=[("union", "Union"), ("non_union", "Non-union")],
                        max_length=12,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("effective_from", models.DateField()),
                ("order", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "rate_id", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.SmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="estimating.estimate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("item", "Item"), ("note", "Note")],
                        default="item",
                        max_length=6,
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("part", models.CharField(blank=True, max_length=160)),
                ("part_norm", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("date_key", models.IntegerField(default=0)),
                (
                    "item_msrp",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "item_map",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("misc", models.BooleanField(default=False)),
                (
                    "lh_union_mobilization",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_field_labor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_union_rough",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_union_pull",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_union_trim",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_union_test",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_engineering",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_fabrication",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_programming",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_commissioning",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "lh_service",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="estimating.catalogitem",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="estimating.room",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["part_norm"],
                name="estimating_item_pn_pattern",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["archived", "manufacturer"], name="estimating_item_arch_mfr"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.UniqueConstraint(
                fields=("source", "part_norm", "manufacturer_raw"),
                name="estimating_item_source_part_mfr",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimateversion",
            constraint=models.UniqueConstraint(
                fields=("estimate", "version_no"), name="estimating_version_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborrate",
            constraint=models.UniqueConstraint(
                fields=("rate_id", "effective_from"), name="estimating_rate_id_date"
            ),
        ),
    ]
