# Generated by Django 5.2.17 on 2026-08-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sl_acct", models.CharField(max_length=16, unique=True)),
                ("description", models.CharField(blank=True, max_length=64)),
                ("sl_acct_type", models.CharField(blank=True, max_length=4)),
                ("sl_group_cd", models.CharField(blank=True, max_length=4)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("contract_value", "Contract Value (budget memo)"),
                            ("labor_wage", "Labor Wages"),
                            ("labor_burden", "Labor Burden"),
                            ("material", "Material"),
                            ("subcontract", "Subcontractor"),
                            ("other_direct", "Other Direct"),
                            ("excluded_memo", "Excluded / Memo"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("sort_num", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_num", "sl_acct"],
            },
        ),
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gl_account", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(blank=True, max_length=64)),
                ("acct_type", models.CharField(blank=True, max_length=4)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectCommercialChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_at", models.DateField()),
                ("field_name", models.CharField(max_length=64)),
                (
                    "prior_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("detected", "Detected from Source Snapshot"),
                            ("manual", "Local Manual Entry"),
                        ],
                        default="detected",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_changes",
                        to="core.project",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLaborRateObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_date", models.DateField()),
                ("labor_account", models.CharField(max_length=16)),
                ("hours", models.DecimalField(decimal_places=4, max_digits=14)),
                ("wage_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "payroll_tax_burden",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "wage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_observations",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "check_date"],
                        name="finance_emp_employe_f5fa6c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "check_date", "labor_account"),
                        name="uniq_employee_rate_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectAccountSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=32)),
                ("sl_acct", models.CharField(max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("contract_value", "Contract Value (budget memo)"),
                            ("labor_wage", "Labor Wages"),
                            ("labor_burden", "Labor Burden"),
                            ("material", "Material"),
                            ("subcontract", "Subcontractor"),
                            ("other_direct", "Other Direct"),
                            ("excluded_memo", "Excluded / Memo"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("is_current", models.BooleanField(default=True)),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "actual_units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "committed_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "eac_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "fac_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "budget_units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_by", models.CharField(blank=True, max_length=10)),
                ("source_updated_prog", models.CharField(blank=True, max_length=8)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_summaries",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "is_current"],
                        name="finance_pro_project_c9b564_idx",
                    ),
                    models.Index(
                        fields=["as_of_date"], name="finance_pro_as_of_d_3735d3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "task_id", "sl_acct", "as_of_date"),
                        name="uniq_account_summary_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectFinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "revenue_budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_labor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "budget_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_subcontract",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_other_direct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_direct_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("budget_touched_after_setup", models.BooleanField(default=False)),
                (
                    "billed_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_wage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_burden",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_hours_sl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "actual_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_subcontract",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_other_direct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_freight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_direct_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "open_commitments_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("last_transaction_date", models.DateField(blank=True, null=True)),
                (
                    "sold_gp_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "sold_gp_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_gp_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_gp_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "effective_loaded_labor_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "earned_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "calculation_version",
                    models.CharField(default="v3.0", max_length=32),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["as_of_date", "project"],
                        name="finance_pro_as_of_d_cf4d85_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "as_of_date"),
                        name="uniq_project_financial_snapshot_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectFinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=64, unique=True)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("sl_acct", models.CharField(max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("contract_value", "Contract Value (budget memo)"),
                            ("labor_wage", "Labor Wages"),
                            ("labor_burden", "Labor Burden"),
                            ("material", "Material"),
                            ("subcontract", "Subcontractor"),
                            ("other_direct", "Other Direct"),
                            ("excluded_memo", "Excluded / Memo"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sub_tag", models.CharField(blank=True, max_length=32)),
                ("system_cd", models.CharField(max_length=2)),
                ("batch_type", models.CharField(blank=True, max_length=4)),
                ("batch_id", models.CharField(max_length=10)),
                ("detail_num", models.IntegerField()),
                ("fiscal_period", models.CharField(max_length=6)),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("posting_date", models.DateField(blank=True, null=True)),
                ("source_created_at", models.DateTimeField()),
                ("source_created_by", models.CharField(blank=True, max_length=10)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("employee_key", models.CharField(blank=True, max_length=10)),
                ("vendor_num", models.CharField(blank=True, max_length=15)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("tr_status", models.CharField(blank=True, max_length=1)),
                ("comment", models.CharField(blank=True, max_length=40)),
                ("pay_period_start", models.DateField(blank=True, null=True)),
                ("pay_period_end", models.DateField(blank=True, null=True)),
                ("voucher_num", models.CharField(blank=True, max_length=10)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_transactions",
                        to="core.employee",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_transactions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "transaction_date"],
                        name="finance_pro_project_a0badd_idx",
                    ),
                    models.Index(
                        fields=["project", "category"],
                        name="finance_pro_project_27947d_idx",
                    ),
                    models.Index(
                        fields=["category", "transaction_date"],
                        name="finance_pro_categor_25a93c_idx",
                    ),
                    models.Index(
                        fields=["employee", "transaction_date"],
                        name="finance_pro_employe_e34cf0_idx",
                    ),
                    models.Index(
                        fields=["source_created_at"],
                        name="finance_pro_source__62530f_idx",
                    ),
                    models.Index(
                        fields=["fiscal_period"], name="finance_pro_fiscal__ccc813_idx"
                    ),
                ],
            },
        ),
    ]
