# Generated by Django 5.2.17 on 2026-08-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_commitments_and_purchase_variance"),
        ("finance", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="actual_purchase_variance",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="open_commitments_subcontract",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="phantom_commitments",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="sl_reported_commitments",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="ProjectCommitmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("sl_acct", models.CharField(max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("contract_value", "Contract Value (budget memo)"),
                            ("labor_wage", "Labor Wages"),
                            ("labor_burden", "Labor Burden"),
                            ("material", "Material"),
                            ("subcontract", "Subcontractor"),
                            ("other_direct", "Other Direct"),
                            ("excluded_memo", "Excluded / Memo"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("open_po", "Open purchase-order line"),
                            (
                                "project_inventory",
                                "Project-inventory allocation (PO receipt at warehouse)",
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                ("system_cd", models.CharField(blank=True, max_length=2)),
                ("batch_type", models.CharField(blank=True, max_length=4)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "qty_shipped_to_project",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_units",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "open_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("is_phantom", models.BooleanField(default=False)),
                ("item_id", models.CharField(blank=True, max_length=32)),
                ("po_number", models.CharField(blank=True, max_length=12)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("promise_date", models.DateField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=12)),
                ("receipt_line", models.CharField(blank=True, max_length=6)),
                ("receipt_date", models.DateField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=40)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("as_of_date", models.DateField()),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_lines",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "sl_acct"],
                        name="finance_pro_project_c86abb_idx",
                    ),
                    models.Index(
                        fields=["source_type", "is_phantom"],
                        name="finance_pro_source__0afa3e_idx",
                    ),
                ],
            },
        ),
    ]
