# Generated by Django 5.2.17 on 2026-08-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_commitments_and_purchase_variance"),
        ("finance", "0002_commitments_and_purchase_variance"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankFigureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(unique=True)),
                (
                    "checking_bank_balance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "float_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "borrowing_base_available",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "credit_line_used",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("payroll_note", models.TextField(blank=True)),
                ("entered_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-entry_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyFinanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(unique=True)),
                ("as_of", models.DateTimeField()),
                ("reconstructed", models.BooleanField(default=False)),
                (
                    "ar_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_current",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_d30",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_d60",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_d90",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_over90",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_credits",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ar_pending",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_current",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_d30",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_d60",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_d90",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ap_over90",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "assets",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "liabilities",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "net_income_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "working_capital",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cash_checking",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cash_payroll",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cash_mma",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cash_petty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "credit_line_gl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "inventory_gl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "revenue_mtd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cogs_mtd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "overhead_mtd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "revenue_prior_month",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cogs_prior_month",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "overhead_prior_month",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("prev_business_day", models.DateField(blank=True, null=True)),
                (
                    "revenue_prev_day_cur",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cost_prev_day_cur",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "revenue_prev_day_prior",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cost_prev_day_prior",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="APOpenDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("vendor_name", models.CharField(blank=True, max_length=64)),
                ("doc_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("days_past_due", models.IntegerField(blank=True, null=True)),
                ("bucket", models.CharField(max_length=8)),
                ("sign", models.SmallIntegerField(default=1)),
                ("doc_bal", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "orig_amt",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("invoice_nbr", models.CharField(blank=True, max_length=40)),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                ("po_nbr", models.CharField(blank=True, max_length=10)),
                ("per_post", models.CharField(blank=True, max_length=6)),
                ("as_of", models.DateTimeField()),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bucket"], name="finance_apo_bucket_02d113_idx"
                    ),
                    models.Index(
                        fields=["vendor_id"], name="finance_apo_vendor__6a3489_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="finance_apo_due_dat_271044_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AROpenDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("customer_name", models.CharField(blank=True, max_length=64)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("order_nbr", models.CharField(blank=True, max_length=15)),
                ("so_type", models.CharField(blank=True, max_length=8)),
                ("book", models.CharField(max_length=10)),
                ("doc_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("days_past_due", models.IntegerField(blank=True, null=True)),
                ("bucket", models.CharField(max_length=8)),
                ("sign", models.SmallIntegerField(default=1)),
                ("doc_bal", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "orig_amt",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("released", models.BooleanField(default=True)),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                ("slsper_id", models.CharField(blank=True, max_length=10)),
                ("terms", models.CharField(blank=True, max_length=4)),
                ("per_post", models.CharField(blank=True, max_length=6)),
                ("cust_po", models.CharField(blank=True, max_length=25)),
                ("as_of", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["book", "bucket"], name="finance_aro_book_e5eae5_idx"
                    ),
                    models.Index(
                        fields=["customer_id_raw"],
                        name="finance_aro_custome_bd5548_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GLAccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acct", models.CharField(max_length=10)),
                ("sub", models.CharField(blank=True, max_length=24)),
                ("fiscal_year", models.CharField(max_length=4)),
                ("acct_type", models.CharField(max_length=2)),
                ("descr", models.CharField(blank=True, max_length=64)),
                (
                    "beg_bal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p00",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p01",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p02",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p03",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p04",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p05",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p06",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p07",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p08",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p09",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p10",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p11",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "p12",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("sl_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fiscal_year", "acct_type"],
                        name="finance_gla_fiscal__c8c702_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("acct", "sub", "fiscal_year"), name="uniq_gl_balance"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GLRecentPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acct", models.CharField(max_length=10)),
                ("sub", models.CharField(blank=True, max_length=24)),
                ("acct_type", models.CharField(max_length=2)),
                ("acct_descr", models.CharField(blank=True, max_length=64)),
                ("tran_date", models.DateField(blank=True, null=True)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                ("per_post", models.CharField(max_length=6)),
                (
                    "dr_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cr_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("module", models.CharField(blank=True, max_length=2)),
                ("batch_nbr", models.CharField(blank=True, max_length=10)),
                ("ref_nbr", models.CharField(blank=True, max_length=10)),
                ("tran_desc", models.CharField(blank=True, max_length=30)),
                ("jrnl_type", models.CharField(blank=True, max_length=3)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["per_post", "acct_type"],
                        name="finance_glr_per_pos_c521ff_idx",
                    ),
                    models.Index(
                        fields=["sl_created_at"], name="finance_glr_sl_crea_7212b6_idx"
                    ),
                ],
            },
        ),
    ]
