# Generated by Django 5.2.17 on 2026-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0003_bankfigureentry_dailyfinancesnapshot_apopendocument_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyfinancesnapshot",
            name="wip_net",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyfinancesnapshot",
            name="wip_overbilled",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyfinancesnapshot",
            name="wip_overbilled_earned",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyfinancesnapshot",
            name="wip_underbilled",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyfinancesnapshot",
            name="wip_underbilled_earned",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
    ]
