# Generated by Django 5.2.17 on 2026-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_wip_earned_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionOverheadShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=4)),
                ("division_code", models.CharField(max_length=3)),
                (
                    "share",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["fiscal_year", "division_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fiscal_year", "division_code"),
                        name="uniq_overhead_share",
                    )
                ],
            },
        ),
    ]
