# Generated by Django 5.2.17 on 2026-08-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_commitments_and_purchase_variance"),
        ("finance", "0007_seed_overhead_shares"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("customer_name", models.CharField(blank=True, max_length=64)),
                ("doc_date", models.DateField(blank=True, null=True)),
                ("batch_nbr", models.CharField(blank=True, max_length=10)),
                (
                    "orig_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("per_post", models.CharField(blank=True, max_length=6)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doc_date"], name="finance_arp_doc_dat_e342d1_idx"
                    ),
                    models.Index(
                        fields=["ref_nbr", "customer_id_raw"],
                        name="finance_arp_ref_nbr_860f6f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ARPaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_ref", models.CharField(max_length=10)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("customer_name", models.CharField(blank=True, max_length=64)),
                ("date_appl", models.DateField(blank=True, null=True)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                ("batch_nbr", models.CharField(blank=True, max_length=10)),
                ("per_appl", models.CharField(blank=True, max_length=6)),
                (
                    "applied",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("invoice_ref", models.CharField(blank=True, max_length=10)),
                ("invoice_type", models.CharField(blank=True, max_length=2)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("terms", models.CharField(blank=True, max_length=4)),
                (
                    "invoice_amt",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "invoice_balance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("invoice_desc", models.CharField(blank=True, max_length=32)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date_appl"], name="finance_arp_date_ap_9efa2a_idx"
                    ),
                    models.Index(
                        fields=["payment_ref", "customer_id_raw"],
                        name="finance_arp_payment_a86376_idx",
                    ),
                ],
            },
        ),
    ]
