# Generated by Django 5.2.17 on 2026-08-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_arpayment_arpaymentapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gl_account", models.CharField(default="10250", max_length=10)),
                ("bank_account", models.CharField(blank=True, max_length=32)),
                ("account_title", models.CharField(blank=True, max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=64)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("file_name", models.CharField(max_length=255)),
                ("file_sha256", models.CharField(max_length=64, unique=True)),
                (
                    "previous_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "ending_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("deposits_count", models.PositiveIntegerField(default=0)),
                (
                    "deposits_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("withdrawals_count", models.PositiveIntegerField(default=0)),
                (
                    "withdrawals_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("checks_count", models.PositiveIntegerField(default=0)),
                (
                    "checks_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("parse_ok", models.BooleanField(default=False)),
                ("parse_notes", models.JSONField(blank=True, default=list)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book_balance_prev",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "book_balance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "residual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-period_end", "gl_account"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gl_account", "period_end"),
                        name="uniq_bank_statement_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField()),
                ("posted_date", models.DateField()),
                ("kind", models.CharField(max_length=16)),
                ("bucket", models.CharField(blank=True, max_length=16)),
                ("description", models.CharField(blank=True, max_length=160)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("check_number", models.CharField(blank=True, max_length=16)),
                ("sl_ref", models.CharField(blank=True, max_length=16)),
                ("payee", models.CharField(blank=True, max_length=64)),
                ("match_kind", models.CharField(blank=True, max_length=64)),
                ("match_detail", models.JSONField(blank=True, default=list)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.bankstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["statement", "line_no"],
                "indexes": [
                    models.Index(
                        fields=["statement", "kind"],
                        name="finance_ban_stateme_4ba9a2_idx",
                    )
                ],
            },
        ),
    ]
