# Generated by Django 5.2.17 on 2026-08-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_employee_is_field_hourly"),
        ("finance", "0009_bankstatement_bankstatementline"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("vendor_name", models.CharField(blank=True, max_length=64)),
                ("doc_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doc_date"], name="finance_apc_doc_dat_41181b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ARInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("customer_name", models.CharField(blank=True, max_length=64)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("order_nbr", models.CharField(blank=True, max_length=15)),
                ("doc_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doc_date"], name="finance_ari_doc_dat_d3967f_idx"
                    ),
                    models.Index(
                        fields=["project"], name="finance_ari_project_31d8c9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="POLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_nbr", models.CharField(max_length=10)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("vendor_name", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, max_length=2)),
                ("buyer", models.CharField(blank=True, max_length=16)),
                ("line_ref", models.CharField(blank=True, max_length=8)),
                ("item_id", models.CharField(blank=True, max_length=32)),
                ("descr", models.CharField(blank=True, max_length=64)),
                (
                    "qty_ord",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "qty_rcvd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "ext_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("site_id", models.CharField(blank=True, max_length=10)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["po_date"], name="finance_pol_po_date_46d3c3_idx"
                    ),
                    models.Index(
                        fields=["project"], name="finance_pol_project_f3501c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="POReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rcpt_nbr", models.CharField(max_length=10)),
                ("rcpt_date", models.DateField(blank=True, null=True)),
                ("po_nbr", models.CharField(blank=True, max_length=10)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("vendor_name", models.CharField(blank=True, max_length=64)),
                ("item_id", models.CharField(blank=True, max_length=32)),
                ("descr", models.CharField(blank=True, max_length=64)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "ext_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rcpt_date"], name="finance_por_rcpt_da_a29466_idx"
                    ),
                    models.Index(
                        fields=["project"], name="finance_por_project_fe66c9_idx"
                    ),
                ],
            },
        ),
    ]
