# Generated by Django 5.2.17 on 2026-08-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_employee_is_field_hourly"),
        ("finance", "0010_apcheck_arinvoice_poline_poreceiptline"),
    ]

    operations = [
        migrations.AddField(
            model_name="poline",
            name="deduce_basis",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="deduced_customer",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="deduced_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="deduced_so",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="deduce_basis",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="deduced_customer",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="deduced_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="deduced_so",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
