# Generated by Django 5.2.17 on 2026-08-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_poline_deduce_basis_poline_deduced_customer_and_more"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_id", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, max_length=2)),
                ("terms", models.CharField(blank=True, max_length=4)),
                ("class_id", models.CharField(blank=True, max_length=12)),
                ("city", models.CharField(blank=True, max_length=32)),
                ("state", models.CharField(blank=True, max_length=4)),
                ("phone", models.CharField(blank=True, max_length=24)),
                ("email", models.CharField(blank=True, max_length=64)),
                ("pmt_method", models.CharField(blank=True, max_length=2)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APCheckApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_ref", models.CharField(max_length=10)),
                ("check_type", models.CharField(max_length=2)),
                ("check_date", models.DateField(blank=True, null=True)),
                ("date_appl", models.DateField(blank=True, null=True)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                (
                    "adj_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "disc_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("voucher_ref", models.CharField(blank=True, max_length=10)),
                ("voucher_type", models.CharField(blank=True, max_length=2)),
                ("voucher_date", models.DateField(blank=True, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("invoice_nbr", models.CharField(blank=True, max_length=40)),
                ("doc_desc", models.CharField(blank=True, max_length=32)),
                (
                    "voucher_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("po_nbr", models.CharField(blank=True, max_length=10)),
                ("terms", models.CharField(blank=True, max_length=4)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["check_ref"], name="finance_apc_check_r_c93cb4_idx"
                    ),
                    models.Index(
                        fields=["vendor_id"], name="finance_apc_vendor__8b547e_idx"
                    ),
                    models.Index(
                        fields=["check_date"], name="finance_apc_check_d_2bcc3e_idx"
                    ),
                ],
            },
        ),
    ]
