# Generated by Django 5.2.17 on 2026-08-29 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_projecttask_sl_created_at_projecttask_sl_created_by_and_more"),
        ("finance", "0012_slvendor_apcheckapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectChangeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("task_description", models.CharField(blank=True, max_length=60)),
                ("event_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("change_order", "Change order"),
                            ("scope_added", "Task / scope added"),
                            ("budget_edited", "Budget edited in place"),
                        ],
                        max_length=16,
                    ),
                ),
                ("field", models.CharField(max_length=32)),
                (
                    "prior_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("entered_by", models.CharField(blank=True, max_length=10)),
                ("source_prog", models.CharField(blank=True, max_length=8)),
                ("source", models.CharField(max_length=16)),
                ("confidence", models.CharField(max_length=16)),
                ("note", models.CharField(blank=True, max_length=160)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_events",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "event_at", "task_id", "field"],
                "indexes": [
                    models.Index(
                        fields=["project", "event_at"],
                        name="finance_pro_project_c5f02b_idx",
                    )
                ],
            },
        ),
    ]
