# Generated by Django 5.2.17 on 2026-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_projectchangeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcommitmentline",
            name="voucher_matched",
            field=models.BooleanField(default=False),
        ),
    ]
