# Generated by Django 5.2.17 on 2026-09-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_projecttask_sl_created_at_projecttask_sl_created_by_and_more"),
        ("finance", "0014_projectcommitmentline_voucher_matched"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(max_length=10)),
                ("doc_type", models.CharField(blank=True, default="", max_length=2)),
                ("doc_date", models.DateField(blank=True, null=True)),
                ("vendor_id", models.CharField(blank=True, default="", max_length=15)),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "freight_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("po_nbr", models.CharField(db_index=True, max_length=10)),
                ("status", models.CharField(blank=True, default="", max_length=2)),
                ("crtd_user", models.CharField(blank=True, default="", max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_nbr", models.CharField(max_length=15)),
                ("line_ref", models.CharField(blank=True, default="", max_length=8)),
                ("ord_date", models.DateField(blank=True, null=True)),
                ("so_type", models.CharField(blank=True, default="", max_length=6)),
                ("behavior", models.CharField(blank=True, default="", max_length=6)),
                ("status", models.CharField(blank=True, default="", max_length=2)),
                ("line_status", models.CharField(blank=True, default="", max_length=2)),
                (
                    "cnet_quote",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                ("crtd_user", models.CharField(blank=True, default="", max_length=16)),
                ("slsper_id", models.CharField(blank=True, default="", max_length=10)),
                (
                    "cust_ord_nbr",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("ship_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "tot_frt",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("item_id", models.CharField(blank=True, default="", max_length=32)),
                ("descr", models.CharField(blank=True, default="", max_length=64)),
                (
                    "qty_ord",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "qty_ship",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "qty_bo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "tot_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "sls_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "tot_ord",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=32)),
                ("site_id", models.CharField(blank=True, default="", max_length=10)),
                ("prom_date", models.DateField(blank=True, null=True)),
                ("req_date", models.DateField(blank=True, null=True)),
                ("drop_ship", models.BooleanField(default=False)),
                (
                    "project_id_raw",
                    models.CharField(blank=True, default="", max_length=16),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipper_id", models.CharField(max_length=15)),
                ("ship_date", models.DateField(blank=True, null=True)),
                ("ship_date_plan", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, default="", max_length=2)),
                ("so_nbr", models.CharField(blank=True, default="", max_length=15)),
                ("invc_nbr", models.CharField(blank=True, default="", max_length=15)),
                ("invc_date", models.DateField(blank=True, null=True)),
                ("crtd_user", models.CharField(blank=True, default="", max_length=16)),
                ("ship_via", models.CharField(blank=True, default="", max_length=16)),
                (
                    "tracking_nbr",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "tot_frt_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "tot_frt_invc",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("line_ref", models.CharField(blank=True, default="", max_length=8)),
                (
                    "ord_line_ref",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("item_id", models.CharField(blank=True, default="", max_length=32)),
                ("descr", models.CharField(blank=True, default="", max_length=64)),
                (
                    "qty_ship",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "tot_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "sls_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "tot_invc",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=32)),
                (
                    "project_id_raw",
                    models.CharField(blank=True, default="", max_length=16),
                ),
            ],
        ),
        migrations.AddField(
            model_name="poline",
            name="cost_vouched",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="crtd_user",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="poline",
            name="last_rcpt_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="open_line",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poline",
            name="po_freight",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="po_type",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="poline",
            name="prom_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="purchase_type",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="poline",
            name="qty_vouched",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="reqd_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poline",
            name="ship_via",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="crtd_user",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="po_line_ref",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="qty_vouched",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="poreceiptline",
            name="vend_invc_nbr",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddIndex(
            model_name="poline",
            index=models.Index(fields=["po_nbr"], name="finance_pol_po_nbr_f09692_idx"),
        ),
        migrations.AddIndex(
            model_name="poreceiptline",
            index=models.Index(fields=["po_nbr"], name="finance_por_po_nbr_59595f_idx"),
        ),
        migrations.AddField(
            model_name="povoucher",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="projectsalesorderline",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="projectsalesorderline",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_so_lines",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="projectshipmentline",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingestion.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="projectshipmentline",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_shipments",
                to="core.project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectsalesorderline",
            index=models.Index(
                fields=["project"], name="finance_pro_project_d93407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectsalesorderline",
            index=models.Index(fields=["so_nbr"], name="finance_pro_so_nbr_83b39f_idx"),
        ),
        migrations.AddIndex(
            model_name="projectshipmentline",
            index=models.Index(
                fields=["project"], name="finance_pro_project_eee596_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectshipmentline",
            index=models.Index(fields=["so_nbr"], name="finance_pro_so_nbr_a349a7_idx"),
        ),
    ]
