# Generated by Django 5.2.17 on 2026-09-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contract_value_reconciliation"),
        ("finance", "0015_project_materials"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="contract_value_basis",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="projectfinancialsnapshot",
            name="contract_value_sl",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.CreateModel(
            name="ContractValueOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("confirm_sl", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=300)),
                ("set_by", models.CharField(blank=True, max_length=120)),
                ("set_at", models.DateTimeField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_value_override",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractValueAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("basis", models.CharField(max_length=32)),
                (
                    "sl_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "effective_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("evidence", models.JSONField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField()),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_value_adjustments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "superseded_at"],
                        name="finance_con_project_626eeb_idx",
                    ),
                    models.Index(
                        fields=["effective_from"], name="finance_con_effecti_2e005c_idx"
                    ),
                ],
            },
        ),
    ]
