# Generated by Django 5.2.17 on 2026-09-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_contract_value_reconciliation"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APVoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_record_id", models.BigIntegerField(unique=True)),
                ("ref_nbr", models.CharField(db_index=True, max_length=10)),
                ("tran_type", models.CharField(max_length=2)),
                ("line_nbr", models.IntegerField(default=0)),
                ("batch_nbr", models.CharField(blank=True, max_length=10)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("tran_date", models.DateField(blank=True, null=True)),
                ("per_post", models.CharField(blank=True, max_length=6)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("dr_cr", models.CharField(blank=True, max_length=1)),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("tran_desc", models.CharField(blank=True, max_length=30)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("po_nbr", models.CharField(blank=True, max_length=10)),
                ("rcpt_nbr", models.CharField(blank=True, max_length=10)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("invt_id", models.CharField(blank=True, max_length=30)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor_id", "tran_date"],
                        name="finance_apv_vendor__d71700_idx",
                    ),
                    models.Index(
                        fields=["gl_subaccount"], name="finance_apv_gl_suba_4feb55_idx"
                    ),
                    models.Index(
                        fields=["project_id_raw"], name="finance_apv_project_c6923a_idx"
                    ),
                    models.Index(
                        fields=["tran_type", "gl_account"],
                        name="finance_apv_tran_ty_97759d_idx",
                    ),
                ],
            },
        ),
    ]
