# Generated by Django 5.2.17 on 2026-09-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_apvoucherline"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POReceiptDist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=16, unique=True)),
                ("rcpt_nbr", models.CharField(db_index=True, max_length=10)),
                ("line_ref", models.CharField(blank=True, max_length=5)),
                ("po_nbr", models.CharField(blank=True, max_length=10)),
                ("vendor_id", models.CharField(blank=True, max_length=15)),
                ("rcpt_date", models.DateField(blank=True, null=True)),
                ("per_post", models.CharField(blank=True, max_length=6)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("invt_id", models.CharField(blank=True, max_length=30)),
                ("descr", models.CharField(blank=True, max_length=60)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "ext_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("so_ord_nbr", models.CharField(blank=True, max_length=15)),
                ("site_id", models.CharField(blank=True, max_length=10)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor_id", "rcpt_date"],
                        name="finance_por_vendor__881b8a_idx",
                    ),
                    models.Index(
                        fields=["gl_subaccount"], name="finance_por_gl_suba_8c7b94_idx"
                    ),
                    models.Index(
                        fields=["project_id_raw"], name="finance_por_project_4b4bd7_idx"
                    ),
                ],
            },
        ),
    ]
