# Generated by Django 5.2.17 on 2026-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_poreceiptdist"),
    ]

    operations = [
        migrations.AddField(
            model_name="apcheck",
            name="cash_acct",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
