# Generated by Django 5.2.17 on 2026-09-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_apcheck_cash_acct"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AROpenInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(db_index=True, max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("line_nbr", models.IntegerField(default=0)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("tran_desc", models.CharField(blank=True, max_length=30)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("invt_id", models.CharField(blank=True, max_length=30)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("tran_date", models.DateField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SLCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("attn", models.CharField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("fax", models.CharField(blank=True, max_length=32)),
                ("email", models.CharField(blank=True, max_length=128)),
                ("bill_name", models.CharField(blank=True, max_length=64)),
                ("bill_attn", models.CharField(blank=True, max_length=64)),
                ("bill_phone", models.CharField(blank=True, max_length=32)),
                ("bill_addr1", models.CharField(blank=True, max_length=64)),
                ("bill_city", models.CharField(blank=True, max_length=32)),
                ("bill_state", models.CharField(blank=True, max_length=4)),
                ("bill_zip", models.CharField(blank=True, max_length=16)),
                ("terms", models.CharField(blank=True, max_length=4)),
                ("stmt_cycle", models.CharField(blank=True, max_length=4)),
                ("stmt_type", models.CharField(blank=True, max_length=2)),
                ("slsper_id", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(blank=True, max_length=2)),
                ("class_id", models.CharField(blank=True, max_length=12)),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("setup_date", models.DateField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
    ]
