# Generated by Django 5.2.17 on 2026-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contract_value_reconciliation"),
        ("finance", "0020_ar_detail"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arinvoice",
            name="cust_po",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="terms",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(
                fields=["customer_id_raw", "doc_date"],
                name="finance_ari_custome_52ad24_idx",
            ),
        ),
    ]
