# Generated by Django 5.2.17 on 2026-09-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contract_value_reconciliation"),
        ("finance", "0021_arinvoice_due_terms"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_nbr", models.CharField(db_index=True, max_length=10)),
                ("doc_type", models.CharField(max_length=2)),
                ("customer_id_raw", models.CharField(blank=True, max_length=15)),
                ("line_nbr", models.IntegerField(default=0)),
                ("kind", models.CharField(default="oth", max_length=3)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("tran_desc", models.CharField(blank=True, max_length=30)),
                ("project_id_raw", models.CharField(blank=True, max_length=16)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("invt_id", models.CharField(blank=True, max_length=30)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("tran_date", models.DateField(blank=True, null=True)),
                ("shipper_id", models.CharField(blank=True, default="", max_length=15)),
                ("order_nbr", models.CharField(blank=True, default="", max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="batch_nbr",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="crtd_prog",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="crtd_user",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="deposits",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="division",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="lupd_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="lupd_user",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="other",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="per_post",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="revenue",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="slsper_id",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="so_type",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="arinvoice",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(
                fields=["sl_created_at"], name="finance_ari_sl_crea_09bd41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(
                fields=["per_post"], name="finance_ari_per_pos_9d0552_idx"
            ),
        ),
        migrations.AddField(
            model_name="arinvoiceline",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingestion.ingestionrun",
            ),
        ),
    ]
