# Generated by Django 5.2.17 on 2026-09-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contract_value_reconciliation"),
        ("finance", "0022_billings"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_id", models.CharField(max_length=10, unique=True)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2
                    ),
                ),
                ("descr", models.CharField(blank=True, max_length=32)),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=9),
                ),
                ("tax_type", models.CharField(blank=True, max_length=2)),
                ("gl_account", models.CharField(blank=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                (
                    "old_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "new_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                ("new_rate_date", models.DateField(blank=True, null=True)),
                ("revised_date", models.DateField(blank=True, null=True)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                ("sl_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sl_updated_by",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesTaxPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tran_date", models.DateField(blank=True, db_index=True, null=True)),
                ("per_post", models.CharField(blank=True, db_index=True, max_length=6)),
                ("module", models.CharField(blank=True, max_length=2)),
                ("jrnl_type", models.CharField(blank=True, max_length=3)),
                ("batch_nbr", models.CharField(blank=True, max_length=10)),
                ("ref_nbr", models.CharField(blank=True, db_index=True, max_length=10)),
                ("gl_subaccount", models.CharField(blank=True, max_length=24)),
                ("tran_desc", models.CharField(blank=True, max_length=30)),
                (
                    "dr_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cr_amt",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("crtd_user", models.CharField(blank=True, default="", max_length=16)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        db_index=True, default="adjustment", max_length=12
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2
                    ),
                ),
                (
                    "state_source",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "period_covered",
                    models.CharField(blank=True, default="", max_length=6),
                ),
                ("period_inferred", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=64)),
                ("doc_type", models.CharField(blank=True, default="", max_length=2)),
                (
                    "customer_id_raw",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("order_nbr", models.CharField(blank=True, default="", max_length=15)),
                (
                    "project_id_raw",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("doc_date", models.DateField(blank=True, null=True)),
                (
                    "doc_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("cust_state", models.CharField(blank=True, default="", max_length=4)),
                (
                    "cust_exempt_nbr",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("shipper_id", models.CharField(blank=True, default="", max_length=15)),
                ("ship_state", models.CharField(blank=True, default="", max_length=4)),
                ("ship_zip", models.CharField(blank=True, default="", max_length=12)),
                ("ship_city", models.CharField(blank=True, default="", max_length=32)),
                ("tax_id", models.CharField(blank=True, default="", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "taxable",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ship_tax",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "state"], name="finance_sal_kind_167ffd_idx"
                    ),
                    models.Index(
                        fields=["state", "per_post"],
                        name="finance_sal_state_2cf75a_idx",
                    ),
                ],
            },
        ),
    ]
