# Generated by Django 5.2.17 on 2026-08-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("market_sector", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("sl_subaccounts", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                ("modelled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_key", models.CharField(max_length=10, unique=True)),
                ("canonical_name", models.CharField(max_length=255)),
                (
                    "ptt_person_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("ptt_employee_type", models.CharField(blank=True, max_length=16)),
                ("ptt_employee_role", models.CharField(blank=True, max_length=16)),
                ("ptt_active", models.BooleanField(null=True)),
                ("sl_status", models.CharField(blank=True, max_length=4)),
                ("home_subaccount", models.CharField(blank=True, max_length=8)),
                ("union_code", models.CharField(blank=True, max_length=10)),
                ("labor_class", models.CharField(blank=True, max_length=10)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "ptt_loaded_rate_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ptt_base_wage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("salesperson_ids", models.JSONField(default=list)),
                (
                    "default_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("salesperson", "Salesperson"),
                            ("estimator", "Estimator"),
                            ("project_manager", "Project Manager"),
                            ("division_head", "Division Head"),
                            ("field", "Field"),
                            ("crew_lead", "Crew Lead (inferred)"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sl_customer_id", models.CharField(max_length=15, unique=True)),
                ("canonical_name", models.CharField(max_length=255)),
                ("sl_class_id", models.CharField(blank=True, max_length=10)),
                ("market_sector_source", models.CharField(blank=True, max_length=64)),
                ("market_sector", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=8)),
                ("sl_status", models.CharField(blank=True, max_length=4)),
                (
                    "default_salesperson_code",
                    models.CharField(blank=True, max_length=10),
                ),
                ("is_general_contractor", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="core.customerfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="Salesperson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("non_commission", models.BooleanField(default=False)),
                ("is_rma_or_split", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salesperson_codes",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_project_number",
                    models.CharField(max_length=32, unique=True),
                ),
                ("display_number", models.CharField(max_length=32)),
                ("sl_project_key_raw", models.CharField(blank=True, max_length=32)),
                (
                    "ptt_project_pk",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("ptt_project_id_raw", models.CharField(blank=True, max_length=64)),
                ("sl_subaccount", models.CharField(blank=True, max_length=8)),
                ("numbering_style", models.CharField(blank=True, max_length=8)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("quote_reference", models.CharField(blank=True, max_length=32)),
                ("customer_po", models.CharField(blank=True, max_length=32)),
                ("contract_type", models.CharField(blank=True, max_length=4)),
                (
                    "project_mode_rule",
                    models.CharField(
                        choices=[
                            ("installation", "Installation / Project"),
                            ("tm_ticket", "T&M Ticket"),
                            ("tm_service", "T&M Service Blanket"),
                            ("service_agreement", "Service Agreement"),
                            ("joc", "JOC Work"),
                            ("warranty", "Warranty"),
                            ("internal", "Internal / Overhead"),
                            ("canceled", "Canceled / Void"),
                            ("template", "Template"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("solution_class", models.CharField(blank=True, max_length=32)),
                ("system_mix", models.JSONField(default=dict)),
                ("work_type_mix", models.JSONField(default=dict)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("awarded_not_started", "Awarded / Not Started"),
                            ("in_progress", "In Progress"),
                            ("field_complete", "Field Complete / Financially Open"),
                            ("closed_stabilizing", "Closed / Stabilizing"),
                            ("closed_stabilized", "Closed / Stabilized"),
                            ("dormant", "Dormant / Stalled"),
                            ("canceled", "Canceled / Void"),
                            ("template", "Template / Internal Bucket"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("lifecycle_rule_version", models.CharField(blank=True, max_length=16)),
                ("lifecycle_evidence", models.JSONField(default=dict)),
                ("sl_status", models.CharField(blank=True, max_length=2)),
                ("ptt_status", models.SmallIntegerField(blank=True, null=True)),
                ("sl_created_at", models.DateTimeField(blank=True, null=True)),
                ("sl_last_updated_at", models.DateTimeField(blank=True, null=True)),
                ("sl_planned_start", models.DateField(blank=True, null=True)),
                ("sl_planned_end", models.DateField(blank=True, null=True)),
                ("ptt_inactivation_date", models.DateField(blank=True, null=True)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("close_date_method", models.CharField(blank=True, max_length=32)),
                ("first_work_date", models.DateField(blank=True, null=True)),
                ("last_work_date", models.DateField(blank=True, null=True)),
                ("last_transaction_date", models.DateField(blank=True, null=True)),
                (
                    "last_transaction_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("financially_stabilized_at", models.DateField(blank=True, null=True)),
                ("salesperson_code", models.CharField(blank=True, max_length=10)),
                ("salesperson_non_commission", models.BooleanField(default=False)),
                ("task_count", models.PositiveIntegerField(default=1)),
                ("is_internal_bucket", models.BooleanField(default=False)),
                ("is_template_or_void", models.BooleanField(default=False)),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "revenue_budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_labor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "budget_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_subcontract",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_other_direct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_direct_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("budget_touched_after_setup", models.BooleanField(default=False)),
                (
                    "contract_value_row_last_edited_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "billed_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_wage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_burden",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_labor_hours_sl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "actual_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_subcontract",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_other_direct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_freight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_direct_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "open_commitments_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "sold_gp_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "sold_gp_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_gp_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_gp_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "effective_loaded_labor_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_labor_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "earned_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ptt_hours_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_onsite",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_ot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_offsite",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "hours_ptt_minus_sl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "hours_last_30_days",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("distinct_workers", models.PositiveIntegerField(default=0)),
                (
                    "pm_remaining_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pm_remaining_hours_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "pm_percent_complete",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "pm_percent_complete_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "labor_percent_complete_calc",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("descriptive_eligible", models.BooleanField(default=False)),
                ("closed_model_eligible", models.BooleanField(default=False)),
                ("award_model_eligible", models.BooleanField(default=False)),
                ("rating_eligible", models.BooleanField(default=False)),
                ("data_quality_flags", models.JSONField(default=list)),
                (
                    "latest_source_observed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.customer",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.division",
                    ),
                ),
                (
                    "division_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_projects",
                        to="core.employee",
                    ),
                ),
                (
                    "estimator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimated_projects",
                        to="core.employee",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to="core.employee",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="core.salesperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-sl_created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("salesperson", "Salesperson"),
                            ("estimator", "Estimator"),
                            ("project_manager", "Project Manager"),
                            ("division_head", "Division Head"),
                            ("field", "Field"),
                            ("crew_lead", "Crew Lead (inferred)"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "assignment_method",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit Source Field"),
                            ("work_log", "Inferred from PTT hours"),
                            ("submitted_by", "Inferred from PTT submitter"),
                            ("manual", "Local Manual Assignment"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "actual_labor_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "share_of_project_hours",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("first_date", models.DateField(blank=True, null=True)),
                ("last_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "role"],
                        name="core_projec_project_9afa88_idx",
                    ),
                    models.Index(
                        fields=["employee", "role"],
                        name="core_projec_employe_ac050a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "employee", "role"),
                        name="uniq_project_employee_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=60)),
                ("sl_status", models.CharField(blank=True, max_length=2)),
                ("task_manager_key", models.CharField(blank=True, max_length=10)),
                ("ptt_phase_pk", models.IntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["task_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "task_id"), name="uniq_project_task"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["division", "lifecycle_state"],
                name="core_projec_divisio_22b5f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["customer"], name="core_projec_custome_af5469_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_manager"], name="core_projec_project_cde0c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["close_date"], name="core_projec_close_d_48f1a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["sl_created_at"], name="core_projec_sl_crea_e4b1f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_mode_rule"], name="core_projec_project_dfe23c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["sl_subaccount"], name="core_projec_sl_suba_e50ba5_idx"
            ),
        ),
    ]
