# Generated by Django 5.2.17 on 2026-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="classification",
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name="employee",
            name="classification_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="classification_inferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="current_wage_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="wage_rate_observed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
