# Generated by Django 5.2.17 on 2026-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_employee_classification_employee_classification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actual_purchase_variance",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="open_commitments_subcontract",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phantom_commitments",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sl_reported_commitments",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
    ]
