# Generated by Django 5.2.17 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_commitments_and_purchase_variance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_field_hourly",
            field=models.BooleanField(default=False),
        ),
    ]
