# Generated by Django 5.2.17 on 2026-08-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_employee_is_field_hourly"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="sl_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="sl_created_by",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="sl_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="sl_updated_by",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
