# Generated by Django 5.2.17 on 2026-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_projecttask_sl_created_at_projecttask_sl_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_value_basis",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_value_evidence",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_value_sl",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
    ]
