# Generated by Django 5.2.17 on 2026-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_search_trigram"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessConfiguration",
            fields=[
                (
                    "key",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
