"""State sales-tax reference for the Sales Tax page — a starting point, not advice. Rates and rules change; the page says
"reference, verify with the state" next to every figure. Compiled 2026-09-08 from the state revenue departments and the
Tax Foundation / TaxCloud 2026 nexus surveys: 41 states set economic nexus at $100,000 of in-state sales, CA / TX / NY
at $500,000, AL / MS at $250,000; 18 jurisdictions still add a 200-transaction test (NY: 100 AND $500K; CT: AND);
Illinois dropped its 200-transaction test on 2026-01-01 and caps the retailer discount at $1,000 a month since 2025.
No statewide rate changed between July 2025 and mid-2026 (Louisiana had moved to 5 % in 2025).

Fields per state: name · base_rate (state-level %, before local add-ons) · local (whether local rates exist) · local_note ·
nexus_sales ($) · nexus_txns (None = sales-only test) · nexus_and (both tests must be met) · sourcing (which rate applies
to a shipped order) · install_labor (separately stated labor to install equipment) · contractor (how a construction
contractor is treated on real-property work — Pace's security / AV installations) · due (return due date) · discount
(vendor / collection allowance) · url. What matters most to Pace: hardware shipped to a customer is tangible personal
property and taxable in every state with a sales tax; installation labor and real-property contracts differ by state.
"""

NO_SALES_TAX = {"AK", "DE", "MT", "NH", "OR"}

STATES = {
    "AL": {"name": "Alabama", "base_rate": 4.0, "local": True, "local_note": "city + county, combined often 9–11 %", "nexus_sales": 250000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials (pays tax on purchases)",
           "due": "20th of the following month", "discount": "5 % of first $100 + 2 % above, max $400 / month", "url": "https://www.revenue.alabama.gov/sales-use/"},
    "AK": {"name": "Alaska", "base_rate": 0.0, "local": True, "local_note": "no state tax; ~100 municipalities levy local sales tax (ARSSTC single filing)", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "per municipality", "contractor": "per municipality",
           "due": "per municipality (ARSSTC: last day of the following month)", "discount": "none", "url": "https://arsstc.org/"},
    "AZ": {"name": "Arizona", "base_rate": 5.6, "local": True, "local_note": "TPT: county + city, combined 7–11 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination for remote sellers", "install_labor": "not taxable when separately stated", "contractor": "prime contracting TPT on modification work; MRRA (repair / replacement) contractors pay tax on materials",
           "due": "20th of the following month", "discount": "none", "url": "https://azdor.gov/transaction-privilege-tax-tpt"},
    "AR": {"name": "Arkansas", "base_rate": 6.5, "local": True, "local_note": "city + county, combined ~9.5 % average", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "generally taxable (installation of taxable goods) — verify", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "2 %, max $1,000 / month", "url": "https://www.dfa.arkansas.gov/excise-tax/sales-and-use-tax/"},
    "CA": {"name": "California", "base_rate": 7.25, "local": True, "local_note": "district taxes on top, combined up to 10.75 %", "nexus_sales": 500000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "origin for the state / local share, destination for district taxes", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials, retailer of fixtures",
           "due": "last day of the following month (quarterly with prepayments for larger filers)", "discount": "none", "url": "https://www.cdtfa.ca.gov/taxes-and-fees/sales-use-tax-rates.htm"},
    "CO": {"name": "Colorado", "base_rate": 2.9, "local": True, "local_note": "home-rule cities self-administer; combined ~7.8 % average", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "vendor fee 4 %, max $1,000 / period (retailers under $1M taxable sales)", "url": "https://tax.colorado.gov/sales-use-tax"},
    "CT": {"name": "Connecticut", "base_rate": 6.35, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": True,
           "sourcing": "destination", "install_labor": "generally taxable (services to commercial property and installation are enumerated) — verify", "contractor": "consumer of materials; services to commercial real property taxable",
           "due": "last day of the following month", "discount": "none", "url": "https://portal.ct.gov/drs/sales-tax/sales-and-use-tax"},
    "DE": {"name": "Delaware", "base_rate": 0.0, "local": False, "local_note": "no sales tax (seller-side gross receipts tax instead)", "nexus_sales": None, "nexus_txns": None, "nexus_and": False,
           "sourcing": "n/a", "install_labor": "n/a", "contractor": "n/a", "due": "n/a", "discount": "n/a", "url": "https://revenue.delaware.gov/"},
    "DC": {"name": "District of Columbia", "base_rate": 6.0, "local": False, "local_note": "single rate", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated — verify", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "none", "url": "https://otr.cfo.dc.gov/page/sales-and-use-taxes"},
    "FL": {"name": "Florida", "base_rate": 6.0, "local": True, "local_note": "county discretionary surtax 0–2.5 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable unless the work is a real-property improvement — verify", "contractor": "consumer on lump-sum real-property contracts",
           "due": "20th of the following month (e-file by the 1st for the allowance)", "discount": "2.5 % of first $1,200, max $30 / return", "url": "https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx"},
    "GA": {"name": "Georgia", "base_rate": 4.0, "local": True, "local_note": "county / MARTA / TSPLOST, combined 6–9 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "3 % of first $3,000 + 0.5 % above (timely)", "url": "https://dor.georgia.gov/taxes/business-taxes/sales-use-tax"},
    "HI": {"name": "Hawaii", "base_rate": 4.0, "local": True, "local_note": "GET; county surcharge 0.5 % (4.5 % Honolulu)", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (GET applies to services)", "contractor": "GET on contracting income",
           "due": "20th of the following month", "discount": "none", "url": "https://tax.hawaii.gov/geninfo/get/"},
    "ID": {"name": "Idaho", "base_rate": 6.0, "local": True, "local_note": "a few resort / auditorium district taxes", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "none", "url": "https://tax.idaho.gov/taxes/sales-use/"},
    "IL": {"name": "Illinois", "base_rate": 6.25, "local": True, "local_note": "home-rule, county, RTA: Chicago 10.25 %, Cook suburbs 9–10.5 %, DuPage ~7–8 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "origin for orders filled from Illinois inventory (the rate at Pace's location = TAX2 7.75 %); destination for remote / out-of-state inventory",
           "install_labor": "not taxable (labor is outside the Retailers' Occupation Tax)", "contractor": "consumer: pays use tax on materials incorporated into real estate, charges the customer no tax; equipment that stays tangible personal property is a taxable retail sale",
           "due": "20th of the following month (ST-1; quarter-monthly prepayments above $20K / month)", "discount": "1.75 %, max $1,000 / month since 2025", "url": "https://tax.illinois.gov/businesses/retailer-resources.html"},
    "IN": {"name": "Indiana", "base_rate": 7.0, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "lump-sum contract: consumer of materials; time-and-materials contract: retail merchant, collects tax on the materials",
           "due": "20th of the following month (30th for smaller filers)", "discount": "collection allowance 0.26–0.73 % by size", "url": "https://www.in.gov/dor/business-tax/sales-tax/"},
    "IA": {"name": "Iowa", "base_rate": 6.0, "local": True, "local_note": "1 % local option in most jurisdictions", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "installation of tangible personal property is an enumerated taxable service — verify", "contractor": "consumer of materials",
           "due": "last day of the following month", "discount": "none", "url": "https://tax.iowa.gov/iowa-sales-and-use-tax-guide"},
    "KS": {"name": "Kansas", "base_rate": 6.5, "local": True, "local_note": "city + county, combined ~8.7 % average", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (labor to install or apply tangible personal property), except original construction", "contractor": "consumer of materials",
           "due": "25th of the following month", "discount": "none", "url": "https://www.ksrevenue.gov/bustaxtypessales.html"},
    "KY": {"name": "Kentucky", "base_rate": 6.0, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "installation charges are generally part of the taxable price — verify", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "1.75 % of first $1,000 + 1.5 % above, max $50 / month", "url": "https://revenue.ky.gov/Business/Sales-Use-Tax/Pages/default.aspx"},
    "LA": {"name": "Louisiana", "base_rate": 5.0, "local": True, "local_note": "parish + city, combined ~10.1 % average (highest in the US); parish returns separate", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month (state and parish)", "discount": "≈0.9 % vendor compensation (capped)", "url": "https://revenue.louisiana.gov/SalesTax"},
    "ME": {"name": "Maine", "base_rate": 5.5, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "15th of the following month", "discount": "none", "url": "https://www.maine.gov/revenue/taxes/sales-use-service-provider-tax"},
    "MD": {"name": "Maryland", "base_rate": 6.0, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "1.2 % of the first $6,000 + 0.9 % above, max $500 / return", "url": "https://www.marylandtaxes.gov/business/sales-use/index.php"},
    "MA": {"name": "Massachusetts", "base_rate": 6.25, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "30th of the following month", "discount": "none", "url": "https://www.mass.gov/guides/sales-and-use-tax"},
    "MI": {"name": "Michigan", "base_rate": 6.0, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "excluded when separately stated (delivery and installation, since 2023)", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "0.5 % of the tax (0.75 % if paid early), capped", "url": "https://www.michigan.gov/taxes/business-taxes/sales-use-tax"},
    "MN": {"name": "Minnesota", "base_rate": 6.875, "local": True, "local_note": "local + transit taxes, combined ~7.5–9 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable when the installed item stays tangible personal property; real-property installation labor is not", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "none", "url": "https://www.revenue.state.mn.us/sales-and-use-tax"},
    "MS": {"name": "Mississippi", "base_rate": 7.0, "local": True, "local_note": "a few city taxes", "nexus_sales": 250000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "installation charges are generally taxable with the goods — verify", "contractor": "3.5 % contractor's tax on commercial contracts over $10,000",
           "due": "20th of the following month", "discount": "2 %, max $50 / month", "url": "https://www.dor.ms.gov/business/sales-and-use-tax"},
    "MO": {"name": "Missouri", "base_rate": 4.225, "local": True, "local_note": "city + county + districts, combined ~8.4 % average", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "origin for in-state sellers; destination (vendor's use tax) for remote sellers", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "2 % timely-payment allowance", "url": "https://dor.mo.gov/taxation/business/tax-types/sales-use/"},
    "MT": {"name": "Montana", "base_rate": 0.0, "local": False, "local_note": "no sales tax (resort-area local taxes only)", "nexus_sales": None, "nexus_txns": None, "nexus_and": False,
           "sourcing": "n/a", "install_labor": "n/a", "contractor": "n/a", "due": "n/a", "discount": "n/a", "url": "https://mtrevenue.gov/"},
    "NE": {"name": "Nebraska", "base_rate": 5.5, "local": True, "local_note": "city taxes up to 2 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable for items that stay tangible personal property — verify", "contractor": "contractor elects Option 1 / 2 / 3 (who pays tax on materials)",
           "due": "20th of the following month", "discount": "collection fee 2.5 % of first $3,000, max $75 / month", "url": "https://revenue.nebraska.gov/businesses/sales-and-use-tax"},
    "NV": {"name": "Nevada", "base_rate": 6.85, "local": True, "local_note": "county rates, combined up to 8.375 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "last day of the following month", "discount": "collection allowance 0.25 %", "url": "https://tax.nv.gov/Sales_Tax/"},
    "NH": {"name": "New Hampshire", "base_rate": 0.0, "local": False, "local_note": "no sales tax", "nexus_sales": None, "nexus_txns": None, "nexus_and": False,
           "sourcing": "n/a", "install_labor": "n/a", "contractor": "n/a", "due": "n/a", "discount": "n/a", "url": "https://www.revenue.nh.gov/"},
    "NJ": {"name": "New Jersey", "base_rate": 6.625, "local": False, "local_note": "no local rates (Urban Enterprise Zones at half rate)", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (installing tangible personal property is an enumerated service) unless it is a capital improvement (certificate ST-8)", "contractor": "consumer of materials; capital-improvement labor exempt",
           "due": "20th of the following month", "discount": "none", "url": "https://www.nj.gov/treasury/taxation/su.shtml"},
    "NM": {"name": "New Mexico", "base_rate": 4.875, "local": True, "local_note": "gross receipts tax; local increments, combined ~7.6 % average", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (gross receipts tax covers services)", "contractor": "gross receipts tax on construction (deductions for subcontractors)",
           "due": "25th of the following month", "discount": "none", "url": "https://www.tax.newmexico.gov/businesses/gross-receipts-overview/"},
    "NY": {"name": "New York", "base_rate": 4.0, "local": True, "local_note": "county + city + MCTD, NYC 8.875 %", "nexus_sales": 500000, "nexus_txns": 100, "nexus_and": True,
           "sourcing": "destination", "install_labor": "taxable (installing tangible personal property) unless the work is a capital improvement (certificate ST-124)", "contractor": "consumer of materials; capital-improvement labor exempt",
           "due": "20th of the month after the quarter (monthly filers above $300K / year)", "discount": "vendor collection credit 5 %, max $200 / quarter", "url": "https://www.tax.ny.gov/bus/st/stidx.htm"},
    "NC": {"name": "North Carolina", "base_rate": 4.75, "local": True, "local_note": "county 2–2.75 %, combined ~7 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (repair, maintenance and installation services since 2016) unless the job is a capital improvement (Form E-589CI)", "contractor": "real-property contractor: consumer of materials on capital improvements",
           "due": "20th of the following month", "discount": "none", "url": "https://www.ncdor.gov/taxes-forms/sales-and-use-tax"},
    "ND": {"name": "North Dakota", "base_rate": 5.0, "local": True, "local_note": "city + county, combined ~7 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "last day of the following month", "discount": "1.5 %, max $110 / month", "url": "https://www.tax.nd.gov/business/sales-and-use-tax"},
    "OH": {"name": "Ohio", "base_rate": 5.75, "local": True, "local_note": "county + transit, combined 6.5–8 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "origin for in-state vendors' intrastate sales; destination for remote sellers", "install_labor": "taxable when the installed item stays tangible personal property", "contractor": "consumer of materials on construction contracts",
           "due": "23rd of the following month", "discount": "0.75 % timely-filing discount", "url": "https://tax.ohio.gov/business/ohio-business-taxes/sales-and-use"},
    "OK": {"name": "Oklahoma", "base_rate": 4.5, "local": True, "local_note": "city + county, combined ~9 % average", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "1 %, max $2,500 / month", "url": "https://oklahoma.gov/tax/businesses/sales-and-use-tax.html"},
    "OR": {"name": "Oregon", "base_rate": 0.0, "local": False, "local_note": "no sales tax", "nexus_sales": None, "nexus_txns": None, "nexus_and": False,
           "sourcing": "n/a", "install_labor": "n/a", "contractor": "n/a", "due": "n/a", "discount": "n/a", "url": "https://www.oregon.gov/dor/"},
    "PA": {"name": "Pennsylvania", "base_rate": 6.0, "local": True, "local_note": "Allegheny +1 %, Philadelphia +2 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable when the installed item stays tangible personal property; real-property installation is a construction contract", "contractor": "consumer of materials on real-property contracts",
           "due": "20th of the following month", "discount": "1 % of tax, capped", "url": "https://www.revenue.pa.gov/TaxTypes/SUT/Pages/default.aspx"},
    "RI": {"name": "Rhode Island", "base_rate": 7.0, "local": False, "local_note": "no local rates", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated — verify", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "none", "url": "https://tax.ri.gov/tax-sections/sales-excise/sales-use-tax"},
    "SC": {"name": "South Carolina", "base_rate": 6.0, "local": True, "local_note": "local option 1–3 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "20th of the following month", "discount": "2 % (3 % under $100 of tax), max $3,000 / year", "url": "https://dor.sc.gov/tax/sales"},
    "SD": {"name": "South Dakota", "base_rate": 4.2, "local": True, "local_note": "municipal 1–2 % (state rate returns to 4.5 % in 2027)", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (services are broadly taxable)", "contractor": "2 % contractor's excise tax on construction",
           "due": "20th of the following month", "discount": "1.5 %, max $70 / month", "url": "https://dor.sd.gov/businesses/taxes/sales-use-tax/"},
    "TN": {"name": "Tennessee", "base_rate": 7.0, "local": True, "local_note": "local 1.5–2.75 % on the first $1,600 of each item; combined ~9.6 % average (2nd highest)", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable when the installed item stays tangible personal property; real-property installation labor is not", "contractor": "consumer of materials on real-property work",
           "due": "20th of the following month", "discount": "none", "url": "https://www.tn.gov/revenue/taxes/sales-and-use-tax.html"},
    "TX": {"name": "Texas", "base_rate": 6.25, "local": True, "local_note": "local up to 2 % (8.25 % cap); remote sellers may use the 1.75 % single local rate", "nexus_sales": 500000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "origin for in-state sellers (the seller's place of business); destination for remote sellers", "install_labor": "taxable when the installed item stays tangible personal property (new construction real-property labor is not)", "contractor": "lump-sum contract: consumer of materials; separated contract: collects tax on the materials",
           "due": "20th of the following month", "discount": "0.5 % timely + 1.25 % prepayment discount", "url": "https://comptroller.texas.gov/taxes/sales/"},
    "UT": {"name": "Utah", "base_rate": 6.1, "local": True, "local_note": "4.85 % state + mandatory local; combined up to ~9 %", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination for shipped orders", "install_labor": "taxable when the installed item stays tangible personal property; separately stated real-property installation is not", "contractor": "consumer of materials on real-property work",
           "due": "last day of the following month", "discount": "seller discount 1.31 % (monthly filers)", "url": "https://tax.utah.gov/sales"},
    "VT": {"name": "Vermont", "base_rate": 6.0, "local": True, "local_note": "1 % local option in some towns", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials",
           "due": "25th of the following month", "discount": "none", "url": "https://tax.vermont.gov/business/sales-and-use-tax"},
    "VA": {"name": "Virginia", "base_rate": 5.3, "local": True, "local_note": "4.3 % state + 1 % local, +0.7 % Northern Virginia / Hampton Roads, +1 % some regions", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "not taxable when separately stated", "contractor": "consumer of materials on real-property work",
           "due": "20th of the following month", "discount": "dealer discount for timely filing (small, tiered by volume)", "url": "https://www.tax.virginia.gov/retail-sales-and-use-tax"},
    "WA": {"name": "Washington", "base_rate": 6.5, "local": True, "local_note": "local up to ~4 %, combined ~9.6 % average; plus B&O tax on gross receipts", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable (a retail sale includes installing and repairing tangible personal property)", "contractor": "retail sales tax on the full construction contract (materials + labor) charged to the customer; B&O on receipts",
           "due": "25th of the following month", "discount": "none", "url": "https://dor.wa.gov/taxes-rates/retail-sales-tax"},
    "WV": {"name": "West Virginia", "base_rate": 6.0, "local": True, "local_note": "1 % municipal tax in many cities", "nexus_sales": 100000, "nexus_txns": 200, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable unless the work is a capital improvement to real property", "contractor": "consumer of materials on capital improvements",
           "due": "20th of the following month", "discount": "none", "url": "https://tax.wv.gov/Business/SalesAndUseTax/Pages/SalesAndUseTax.aspx"},
    "WI": {"name": "Wisconsin", "base_rate": 5.0, "local": True, "local_note": "0.5 % county in most counties; Milwaukee county 0.9 % + city 2 % since 2024", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable when the installed item stays tangible personal property; real-property improvement labor is not", "contractor": "consumer of materials on real-property work",
           "due": "last day of the following month", "discount": "retailer's discount 0.5 % (capped)", "url": "https://www.revenue.wi.gov/Pages/FAQS/pcs-sales.aspx"},
    "WY": {"name": "Wyoming", "base_rate": 4.0, "local": True, "local_note": "county 1–2 %", "nexus_sales": 100000, "nexus_txns": None, "nexus_and": False,
           "sourcing": "destination", "install_labor": "taxable for services to tangible personal property — verify", "contractor": "consumer of materials",
           "due": "last day of the following month", "discount": "vendor compensation 1.95 %, max $500 / month", "url": "https://revenue.wyo.gov/divisions/excise-tax-division"},
}


def state_name(code):
    s = STATES.get((code or "").upper())
    return s["name"] if s else (code or "")


def taxes_sales(code):
    return (code or "").upper() in STATES and (code or "").upper() not in NO_SALES_TAX
