# Generated by Django 5.2.17 on 2026-09-10 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bids", "0002_bidclientalias_candidates"),
        ("core", "0007_search_trigram"),
        ("ingestion", "0002_alter_dataqualityissue_source_system_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sharepoint_drive", "SharePoint library"),
                            ("share", "Network share"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("site_path", models.CharField(blank=True, max_length=128)),
                ("drive_id", models.CharField(blank=True, max_length=128)),
                ("root_path", models.CharField(blank=True, max_length=500)),
                ("web_url", models.URLField(blank=True, max_length=500)),
                ("division", models.CharField(blank=True, max_length=8)),
                ("delta_link", models.TextField(blank=True)),
                ("last_indexed", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("file_count", models.PositiveIntegerField(default=0)),
                ("folder_count", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=255)),
                ("ext", models.CharField(blank=True, max_length=16)),
                ("size", models.BigIntegerField(default=0)),
                ("mtime", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("modified_by", models.CharField(blank=True, max_length=128)),
                ("etag", models.CharField(blank=True, max_length=128)),
                ("web_url", models.URLField(blank=True, max_length=1000)),
                ("unc", models.CharField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "text_status",
                    models.CharField(
                        choices=[
                            ("none", "Not extracted"),
                            ("ok", "Extracted"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("text_error", models.CharField(blank=True, max_length=300)),
                ("checked_etag", models.CharField(blank=True, max_length=128)),
                ("link_rule", models.CharField(blank=True, max_length=32)),
                (
                    "link_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("link_via", models.CharField(blank=True, max_length=8)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "linked_bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="bids.bid",
                    ),
                ),
                (
                    "linked_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.customer",
                    ),
                ),
                (
                    "linked_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extractor", models.CharField(max_length=32)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("page_offsets", models.JSONField(default=list)),
                ("text", models.TextField(blank=True)),
                ("chars", models.PositiveIntegerField(default=0)),
                ("truncated", models.BooleanField(default=False)),
                ("extracted_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text",
                        to="documents.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=255)),
                ("item_id", models.CharField(max_length=255)),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("mtime", models.DateTimeField(blank=True, null=True)),
                ("web_url", models.URLField(blank=True, max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="documents.folder",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="documents.repo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="documents.folder",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="repo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="documents.repo",
            ),
        ),
        migrations.CreateModel(
            name="DocFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_id", models.CharField(max_length=48)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                        ],
                        default="warn",
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("fixed", "Fixed"),
                        ],
                        default="open",
                        max_length=14,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_findings",
                        to="bids.bid",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_findings",
                        to="core.project",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="documents.file",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="documents_d_status_924a49_idx",
                    ),
                    models.Index(
                        fields=["check_id"], name="documents_d_check_i_64b92a_idx"
                    ),
                    models.Index(fields=["bid"], name="documents_d_bid_id_87799d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file", "fingerprint"), name="uniq_finding_file_fp"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule", models.CharField(max_length=32)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("dedupe", models.CharField(max_length=80, unique=True)),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_links",
                        to="bids.bid",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_links",
                        to="core.customer",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_links",
                        to="core.project",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.folder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project"], name="documents_d_project_57f330_idx"
                    ),
                    models.Index(fields=["bid"], name="documents_d_bid_id_4fe70d_idx"),
                    models.Index(
                        fields=["customer"], name="documents_d_custome_c0c300_idx"
                    ),
                    models.Index(fields=["state"], name="documents_d_state_f29ee6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("readable", models.BooleanField(default=False)),
                ("web_url", models.URLField(blank=True, max_length=1000)),
                ("seen_at", models.DateTimeField(auto_now=True)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="bids.bid",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bid", "name"), name="uniq_attachment_bid_name"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["repo", "path"], name="documents_f_repo_id_73f953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["repo", "depth"], name="documents_f_repo_id_15c692_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                fields=("repo", "item_id"), name="uniq_folder_repo_item"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["repo", "path"], name="documents_f_repo_id_8caf53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["linked_project"], name="documents_f_linked__d14caf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["linked_bid"], name="documents_f_linked__a5680d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["mtime"], name="documents_f_mtime_44cf8e_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["ext"], name="documents_f_ext_86b018_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["text_status"], name="documents_f_text_st_c7ecfb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("repo", "item_id"), name="uniq_file_repo_item"
            ),
        ),
    ]
