# Generated by Django 5.2.17 on 2026-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="walked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
