# Generated by Django 5.2.17 on 2026-08-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("ptt", "PTT"),
                            ("sl", "Microsoft Dynamics SL"),
                            ("local", "Pace Company Analytics"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("nightly", "Nightly"),
                            ("manual", "Manual"),
                            ("backfill", "Backfill"),
                            ("retry", "Retry"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("watermark_start", models.JSONField(blank=True, default=dict)),
                ("watermark_end", models.JSONField(blank=True, default=dict)),
                ("rows_read", models.BigIntegerField(default=0)),
                ("rows_inserted", models.BigIntegerField(default=0)),
                ("rows_updated", models.BigIntegerField(default=0)),
                ("rows_unchanged", models.BigIntegerField(default=0)),
                ("rows_rejected", models.BigIntegerField(default=0)),
                ("query_versions", models.JSONField(blank=True, default=dict)),
                ("permissions_audit", models.JSONField(blank=True, default=dict)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("code_commit", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.TextField(blank=True)),
                ("log_path", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefreshRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("scope", models.CharField(default="all", max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("blocking", "Blocking"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted Limitation"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ptt", "PTT"),
                            ("sl", "Microsoft Dynamics SL"),
                            ("local", "Pace Company Analytics"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=255)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                ("details", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_quality_issues",
                        to="core.project",
                    ),
                ),
                (
                    "detected_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="ingestion_d_code_d3add8_idx"
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="ingestion_d_severit_556544_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "project", "source_key", "field_name"),
                        name="uniq_open_issue_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceRecordVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("ptt", "PTT"),
                            ("sl", "Microsoft Dynamics SL"),
                            ("local", "Pace Company Analytics"),
                        ],
                        max_length=16,
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("source_key", models.CharField(max_length=255)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "first_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="first_seen_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_seen_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_system", "entity_type", "source_key"],
                        name="ingestion_s_source__e66109_idx",
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="ingestion_s_last_se_98999f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_system",
                            "entity_type",
                            "source_key",
                            "content_hash",
                        ),
                        name="uniq_source_record_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceWatermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("ptt", "PTT"),
                            ("sl", "Microsoft Dynamics SL"),
                            ("local", "Pace Company Analytics"),
                        ],
                        max_length=16,
                    ),
                ),
                ("query_name", models.CharField(max_length=128)),
                ("watermark", models.JSONField(default=dict)),
                (
                    "last_successful_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "query_name"),
                        name="uniq_source_query_watermark",
                    )
                ],
            },
        ),
    ]
