# Generated by Django 5.2.17 on 2026-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityissue",
            name="source_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ptt", "PTT"),
                    ("sl", "Microsoft Dynamics SL"),
                    ("local", "Pace Company Analytics"),
                    ("sharepoint", "SharePoint (Graph)"),
                    ("planner", "Microsoft Planner"),
                    ("share", "Network share (P:)"),
                    ("cnet", "ChannelOnline"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("ptt", "PTT"),
                    ("sl", "Microsoft Dynamics SL"),
                    ("local", "Pace Company Analytics"),
                    ("sharepoint", "SharePoint (Graph)"),
                    ("planner", "Microsoft Planner"),
                    ("share", "Network share (P:)"),
                    ("cnet", "ChannelOnline"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="sourcerecordversion",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("ptt", "PTT"),
                    ("sl", "Microsoft Dynamics SL"),
                    ("local", "Pace Company Analytics"),
                    ("sharepoint", "SharePoint (Graph)"),
                    ("planner", "Microsoft Planner"),
                    ("share", "Network share (P:)"),
                    ("cnet", "ChannelOnline"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="sourcewatermark",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("ptt", "PTT"),
                    ("sl", "Microsoft Dynamics SL"),
                    ("local", "Pace Company Analytics"),
                    ("sharepoint", "SharePoint (Graph)"),
                    ("planner", "Microsoft Planner"),
                    ("share", "Network share (P:)"),
                    ("cnet", "ChannelOnline"),
                ],
                max_length=16,
            ),
        ),
    ]
