# Generated by Django 5.2.17 on 2026-09-10 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_search_trigram"),
        ("ingestion", "0002_alter_dataqualityissue_source_system_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sp_item_id", models.CharField(max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("list", "Project List"),
                            ("archive", "Project Archive"),
                        ],
                        default="list",
                        max_length=8,
                    ),
                ),
                ("portal_project_id", models.CharField(blank=True, max_length=32)),
                ("job_number_raw", models.CharField(blank=True, max_length=64)),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("stage", models.CharField(default="unknown", max_length=16)),
                ("stage_flag", models.CharField(blank=True, max_length=24)),
                ("status_raw", models.CharField(blank=True, max_length=64)),
                ("bid_due", models.DateField(blank=True, null=True)),
                ("submitted_on", models.DateField(blank=True, null=True)),
                ("awarded_on", models.DateField(blank=True, null=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("bidder_raw", models.CharField(blank=True, max_length=64)),
                ("estimator_inferred", models.BooleanField(default=False)),
                ("estimator_rule", models.CharField(blank=True, max_length=32)),
                ("sales_rep_raw", models.CharField(blank=True, max_length=64)),
                ("house_account", models.BooleanField(default=False)),
                ("probability", models.SmallIntegerField(blank=True, null=True)),
                ("pct_close_raw", models.CharField(blank=True, max_length=24)),
                ("ball_in_court", models.CharField(blank=True, max_length=64)),
                ("bom_status", models.CharField(blank=True, max_length=32)),
                ("walkthrough_date", models.DateField(blank=True, null=True)),
                ("walkthrough_raw", models.CharField(blank=True, max_length=64)),
                ("po_number", models.CharField(blank=True, max_length=64)),
                ("sales_order", models.CharField(blank=True, max_length=32)),
                ("comments", models.TextField(blank=True)),
                ("attachments_flag", models.BooleanField(default=False)),
                ("created_by_raw", models.CharField(blank=True, max_length=128)),
                ("portal_created", models.DateTimeField(blank=True, null=True)),
                ("portal_modified", models.DateTimeField(blank=True, null=True)),
                ("web_url", models.URLField(blank=True, max_length=500)),
                ("division", models.CharField(blank=True, max_length=8)),
                ("won_by_sl", models.BooleanField(default=False)),
                ("versions_synced_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bids",
                        to="core.customer",
                    ),
                ),
                (
                    "estimator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimated_bids",
                        to="core.employee",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bids",
                        to="core.project",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rep_bids",
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidClientAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.CharField(max_length=255, unique=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("rule", models.CharField(blank=True, max_length=32)),
                ("manual", models.BooleanField(default=False)),
                ("uses", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bid_aliases",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BidderAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.CharField(max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("estimator", "Estimator (Bidder)"),
                            ("sales_rep", "Sales Rep"),
                            ("walkthrough", "Walkthrough personnel"),
                            ("pm", "Project Manager"),
                        ],
                        default="estimator",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("rule", models.CharField(blank=True, max_length=32)),
                ("manual", models.BooleanField(default=False)),
                ("candidates", models.JSONField(default=list)),
                ("uses", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bid_aliases",
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidFollowup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                ("due", models.DateField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="bids.bid",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["done_at", "due", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BidNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("client", "Client follow-up"),
                            ("internal", "Internal note"),
                            ("pricing", "Pricing question"),
                            ("risk", "Risk / blocker"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("author_name", models.CharField(blank=True, max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="bids.bid",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BidRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("mitigation", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="bids.bid",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["closed_at", "-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BidSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("division", models.CharField(blank=True, max_length=8)),
                ("stage", models.CharField(max_length=16)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "weighted_value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("aged_30", models.PositiveIntegerField(default=0)),
                ("aged_60", models.PositiveIntegerField(default=0)),
                (
                    "estimator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_no", models.CharField(max_length=16)),
                ("modified_at", models.DateTimeField()),
                ("modified_by", models.CharField(blank=True, max_length=128)),
                ("stage", models.CharField(default="unknown", max_length=16)),
                ("status_raw", models.CharField(blank=True, max_length=64)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("bidder_raw", models.CharField(blank=True, max_length=64)),
                ("probability", models.SmallIntegerField(blank=True, null=True)),
                ("job_number_raw", models.CharField(blank=True, max_length=64)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="bids.bid",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["stage"], name="bids_bid_stage_70bae4_idx"),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["estimator", "stage"], name="bids_bid_estimat_7a8cb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["division", "stage"], name="bids_bid_divisio_fd227d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["bid_due"], name="bids_bid_bid_due_20a0af_idx"),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["project"], name="bids_bid_project_7740dd_idx"),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("source", "sp_item_id"), name="uniq_bid_source_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidderalias",
            constraint=models.UniqueConstraint(
                fields=("raw", "role"), name="uniq_alias_raw_role"
            ),
        ),
        migrations.AddIndex(
            model_name="bidsnapshot",
            index=models.Index(
                fields=["snapshot_date"], name="bids_bidsna_snapsho_99fdb6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "division", "estimator", "stage"),
                name="uniq_bid_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="bidversion",
            index=models.Index(
                fields=["bid", "modified_at"], name="bids_bidver_bid_id_a384c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidversion",
            constraint=models.UniqueConstraint(
                fields=("bid", "version_no"), name="uniq_bid_version"
            ),
        ),
    ]
