# Generated by Django 5.2.17 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bids", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidclientalias",
            name="candidates",
            field=models.JSONField(default=list),
        ),
    ]
