# Generated by Django 5.2.17 on 2026-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bids", "0002_bidclientalias_candidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="pm_raw",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
