# Generated by Django 5.2.17 on 2026-09-10 17:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("core", "0007_search_trigram"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "trade",
                    models.CharField(
                        choices=[("Union", "Union"), ("Non-Union", "Non-Union")],
                        default="Union",
                        max_length=16,
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "weekend",
                    models.CharField(
                        choices=[
                            ("none", "Weekdays only"),
                            ("sat", "+ include Saturdays"),
                            ("sun", "+ include Sundays"),
                            ("both", "+ include Sat & Sun"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("dates", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_short", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["plan_project_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PhaseRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "weekend",
                    models.CharField(
                        choices=[
                            ("none", "Weekdays only"),
                            ("sat", "+ include Saturdays"),
                            ("sun", "+ include Sundays"),
                            ("both", "+ include Sat & Sun"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="scheduling.planphase",
                    ),
                ),
            ],
            options={
                "ordering": ["phase_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlanProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("pm_raw", models.CharField(blank=True, max_length=64)),
                ("division", models.CharField(blank=True, max_length=8)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("access_start", models.TimeField(default=datetime.time(7, 0))),
                ("access_end", models.TimeField(default=datetime.time(15, 0))),
                ("days", models.JSONField(blank=True, default=list)),
                ("hours_per_day", models.PositiveSmallIntegerField(default=8)),
                (
                    "hours_union",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "hours_nonunion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("colour", models.CharField(blank=True, max_length=9)),
                ("short_project", models.BooleanField(default=False)),
                ("completed_early", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="manual", max_length=32)),
                ("status_row_id", models.IntegerField(blank=True, null=True)),
                ("unscheduled", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("legacy_id", models.CharField(blank=True, max_length=40)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
                (
                    "pm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_projects",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="planphase",
            name="plan_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="scheduling.planproject",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=120)),
                ("sort_name", models.CharField(blank=True, max_length=120)),
                (
                    "trade",
                    models.CharField(
                        choices=[
                            ("Union", "Union"),
                            ("Subcontracted Union", "Subcontracted Union"),
                            ("Non-Union", "Non-Union"),
                        ],
                        default="Union",
                        max_length=24,
                    ),
                ),
                ("max_weekly", models.PositiveSmallIntegerField(default=40)),
                ("divisions", models.JSONField(blank=True, default=list)),
                ("approved_ot", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("source", models.CharField(default="manual", max_length=16)),
                ("legacy_id", models.CharField(blank=True, max_length=40)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduler_resource",
                        to="core.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_name", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ResourcePto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pto",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("hours", models.DecimalField(decimal_places=1, max_digits=4)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("legacy_id", models.CharField(blank=True, max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="scheduling.planphase",
                    ),
                ),
                (
                    "plan_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.planproject",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "resource_id"],
                "indexes": [
                    models.Index(
                        fields=["resource", "date"],
                        name="scheduling__resourc_dc5f80_idx",
                    ),
                    models.Index(
                        fields=["plan_project", "date"],
                        name="scheduling__plan_pr_8bfda9_idx",
                    ),
                ],
            },
        ),
    ]
