# Generated by Django 5.2.17 on 2026-09-10 17:43

import apps.planning.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bids", "0002_bidclientalias_candidates"),
        ("core", "0007_search_trigram"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PunchDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StatusVocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("bg", models.CharField(default="#ffffff", max_length=9)),
                ("fg", models.CharField(default="#606a71", max_length=9)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "status vocabulary",
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_name", models.CharField(max_length=150)),
                ("project_number_raw", models.CharField(blank=True, max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[("BOM", "BOM"), ("Labor", "Labor")], max_length=8
                    ),
                ),
                ("requested_by_raw", models.CharField(blank=True, max_length=100)),
                ("approver_raw", models.CharField(blank=True, max_length=100)),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("reopened", "Reopened"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(db_index=True)),
                ("decided_by_raw", models.CharField(blank=True, max_length=100)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("estimate_id", models.IntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("planner", "Planner"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_to_approve",
                        to="core.employee",
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="bids.bid",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="core.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("edited", "edited"),
                            ("approved", "approved"),
                            ("reopened", "reopened"),
                            ("deleted", "deleted"),
                            ("attachment_added", "attachment_added"),
                            ("attachment_removed", "attachment_removed"),
                            ("imported", "imported"),
                        ],
                        max_length=24,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="planning.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.planning.models.attachment_storage,
                        upload_to=apps.planning.models._attachment_path,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="planning.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PunchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("date_entered", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("bic", models.CharField(blank=True, max_length=60)),
                ("critical", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("due_by", models.DateField(blank=True, null=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("assigned", models.CharField(blank=True, max_length=200)),
                ("engineer_signoff", models.CharField(blank=True, max_length=200)),
                ("verified", models.CharField(blank=True, max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["punch_project", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PunchAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.planning.models.attachment_storage,
                        upload_to="punch/%Y/%m/",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="planning.punchitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PunchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("division", models.CharField(db_index=True, max_length=8)),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("pm_raw", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("planner", "Planner"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_projects",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_projects",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["division", "code"],
                "unique_together": {("division", "code")},
            },
        ),
        migrations.AddField(
            model_name="punchitem",
            name="punch_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="planning.punchproject",
            ),
        ),
        migrations.CreateModel(
            name="PunchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("field", models.CharField(max_length=40)),
                ("old", models.TextField(blank=True)),
                ("new", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="planning.punchitem",
                    ),
                ),
                (
                    "punch_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="planning.punchproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StatusRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_number_raw", models.CharField(blank=True, max_length=32)),
                ("name", models.CharField(max_length=300)),
                ("division", models.CharField(db_index=True, max_length=8)),
                ("task_num", models.IntegerField(blank=True, null=True)),
                ("phase_status", models.CharField(blank=True, max_length=64)),
                ("equipment_status", models.CharField(blank=True, max_length=64)),
                ("pm_raw", models.CharField(blank=True, max_length=120)),
                ("pm2_raw", models.CharField(blank=True, max_length=120)),
                ("engineer", models.CharField(blank=True, max_length=120)),
                ("foreman", models.CharField(blank=True, max_length=120)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "hours_left",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "percent",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("site_contact", models.CharField(blank=True, max_length=300)),
                ("assigned_to", models.CharField(blank=True, max_length=300)),
                ("priority_raw", models.CharField(blank=True, max_length=32)),
                ("last_update_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("planner", "Planner"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "source_key",
                    models.CharField(blank=True, db_index=True, max_length=140),
                ),
                ("planner_task_id", models.CharField(blank=True, max_length=64)),
                ("sent_to_scheduler_at", models.DateTimeField(blank=True, null=True)),
                ("plan_project_id", models.IntegerField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_status_rows",
                        to="core.employee",
                    ),
                ),
                (
                    "pm2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_status_rows_pm2",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_rows",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["division", "task_num", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("field", models.CharField(max_length=40)),
                ("old", models.TextField(blank=True)),
                ("new", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="planning.statusrow",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="statusrow",
            index=models.Index(
                fields=["division", "completed"], name="planning_st_divisio_ca31ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statusrow",
            index=models.Index(
                fields=["project"], name="planning_st_project_316cff_idx"
            ),
        ),
    ]
