# Generated by Django 5.2.17 on 2026-08-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PercentCompleteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                (
                    "ptt_percent_complete",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("ptt_last_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sl_pm_id26_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "ptt_remaining_expense_costs",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ptt_remaining_labor_costs",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="percent_complete_observations",
                        to="core.project",
                    ),
                ),
                (
                    "ptt_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "observed_at"), name="uniq_pc_observation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectOperationalSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                (
                    "ptt_hours_to_date",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_onsite_to_date",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_ot_to_date",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ptt_hours_offsite_to_date",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "sl_labor_hours_to_date",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "hours_ptt_minus_sl",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pm_remaining_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pm_remaining_hours_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "budget_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "pm_percent_complete",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "pm_percent_complete_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "labor_percent_complete_calc",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "hours_last_7_days",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_last_30_days",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_last_90_days",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("active_workers_last_30_days", models.PositiveIntegerField(default=0)),
                ("distinct_workers_to_date", models.PositiveIntegerField(default=0)),
                ("days_since_last_work", models.IntegerField(blank=True, null=True)),
                ("first_work_date", models.DateField(blank=True, null=True)),
                ("last_work_date", models.DateField(blank=True, null=True)),
                ("system_mix", models.JSONField(default=dict)),
                ("work_type_mix", models.JSONField(default=dict)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["as_of_date", "project"],
                        name="operations__as_of_d_cc7792_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "as_of_date"),
                        name="uniq_project_operational_snapshot_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RemainingHoursRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revised_at", models.DateTimeField()),
                ("ptt_person_pk", models.IntegerField(blank=True, null=True)),
                (
                    "remaining_hours_non_union",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "remaining_hours_union",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "remaining_hours_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remaining_hours_revisions",
                        to="core.project",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["revised_at", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["project", "revised_at"],
                        name="operations__project_0d61b2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "revised_at", "sequence"),
                        name="uniq_remaining_hours_revision",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.IntegerField(unique=True)),
                ("task_id_text", models.CharField(blank=True, max_length=32)),
                ("ptt_person_pk", models.IntegerField()),
                ("ptt_submitted_by_pk", models.IntegerField(blank=True, null=True)),
                ("form_type", models.SmallIntegerField()),
                ("work_date", models.DateField()),
                (
                    "hours_onsite",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_ot",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_offsite",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "hours_time_off",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("system_choice", models.CharField(blank=True, max_length=32)),
                ("work_type_choice", models.CharField(blank=True, max_length=32)),
                ("completed_flag", models.BooleanField(null=True)),
                ("activity_note", models.TextField(blank=True)),
                ("open_issues_note", models.TextField(blank=True)),
                ("shift_code", models.CharField(blank=True, max_length=16)),
                (
                    "shift_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("source_status", models.SmallIntegerField(default=1)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("hours_parse_warning", models.BooleanField(default=False)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="core.employee",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="core.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_time_entries",
                        to="core.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="core.projecttask",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "work_date"],
                        name="operations__project_fb8d49_idx",
                    ),
                    models.Index(
                        fields=["employee", "work_date"],
                        name="operations__employe_cf1c62_idx",
                    ),
                    models.Index(
                        fields=["work_date"], name="operations__work_da_037730_idx"
                    ),
                    models.Index(
                        fields=["source_status"], name="operations__source__1a4ded_idx"
                    ),
                ],
            },
        ),
    ]
