# Generated by Django 5.2.17 on 2026-08-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("as_of_date", models.DateField()),
                ("methodology_version", models.CharField(max_length=32)),
                ("training_cutoff", models.DateField()),
                ("status", models.CharField(default="succeeded", max_length=16)),
                ("metrics", models.JSONField(default=dict)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-as_of_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("generated_at", models.DateTimeField()),
                (
                    "prediction_method",
                    models.CharField(default="deterministic", max_length=32),
                ),
                ("labor_rate_method", models.CharField(blank=True, max_length=32)),
                (
                    "labor_rate_used",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "unposted_labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "unposted_labor_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "remaining_labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "remaining_labor_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "eac_labor_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_material",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_subcontract",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_other_direct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_direct_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_gp_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "eac_gp_percent",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "projected_margin_change_points",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "projected_gp_shortfall_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "hours_overrun_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, max_length=16)),
                ("risk_reasons", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["as_of_date", "risk_level"],
                        name="analytics_p_as_of_d_9ca77c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "as_of_date"),
                        name="uniq_project_prediction_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("customer_family", "Customer Family"),
                            ("sector", "Market Sector"),
                            ("solution", "Solution / Project Type"),
                            ("project_mode", "Project Mode"),
                            ("project_manager", "Project Manager"),
                            ("estimator", "Estimator"),
                            ("salesperson", "Salesperson"),
                            ("division_head_era", "Division Head Era"),
                            ("field_employee", "Field Employee"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_key", models.CharField(max_length=128)),
                ("entity_name", models.CharField(max_length=255)),
                ("metric_name", models.CharField(max_length=128)),
                (
                    "raw_effect",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "adjusted_effect",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "interval_low",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "interval_high",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "standard_error",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("project_count", models.PositiveIntegerField(default=0)),
                (
                    "effective_project_count",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "revenue_exposure",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "labor_hours_exposure",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("customer_count", models.PositiveIntegerField(default=0)),
                ("solution_count", models.PositiveIntegerField(default=0)),
                (
                    "shrinkage_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "reliability_score",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "percentile",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "display_index",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "raw_mean_outcome",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("insufficient", "Insufficient Data"),
                            ("provisional", "Provisional"),
                            ("publishable", "Publishable"),
                            ("not_identifiable", "Not Identifiable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("limitations", models.JSONField(default=list)),
                ("detail", models.JSONField(default=dict)),
                (
                    "rating_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="analytics.ratingrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "metric_name", "publication_status"],
                        name="analytics_e_entity__40ebb3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "rating_run",
                            "entity_type",
                            "entity_key",
                            "metric_name",
                        ),
                        name="uniq_entity_rating_metric_run",
                    )
                ],
            },
        ),
    ]
