# Generated by Django 5.2.17 on 2026-09-17 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0002_permissions_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("can_create_reports", models.BooleanField(default=False)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="report_groups", to="access.account"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("storage_name", models.CharField(max_length=80)),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reports",
                        to="access.account",
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        blank=True, related_name="readable_reports", to="access.account"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="reports.reportgroup"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
