# Generated by Django 5.2.17 on 2026-08-27 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_commitments_and_purchase_variance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("is_superadmin", models.BooleanField(default=False)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accounts",
                        to="access.account",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="core.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pca_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "login"),
                            ("login_denied", "login_denied"),
                            ("logout", "logout"),
                            ("page_view", "page_view"),
                            ("denied", "denied"),
                            ("account_created", "account_created"),
                            ("account_disabled", "account_disabled"),
                            ("account_enabled", "account_enabled"),
                            ("role_granted", "role_granted"),
                            ("role_revoked", "role_revoked"),
                            ("extra_granted", "extra_granted"),
                            ("extra_revoked", "extra_revoked"),
                            ("superadmin_changed", "superadmin_changed"),
                            ("impersonation_start", "impersonation_start"),
                            ("impersonation_stop", "impersonation_stop"),
                            ("write_action", "write_action"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("capability_or_role", models.SlugField(blank=True, max_length=48)),
                ("view_name", models.CharField(blank=True, max_length=64)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("division", models.CharField(blank=True, max_length=8)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "acting_as",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="access.account",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "at"], name="access_audi_actor_i_e64780_idx"
                    ),
                    models.Index(
                        fields=["kind", "at"], name="access_audi_kind_f66531_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtraGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capability", models.SlugField(max_length=48)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_grants",
                        to="access.account",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "capability")},
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.SlugField(max_length=32)),
                ("division_codes", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="access.account",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "role")},
            },
        ),
    ]
