# Generated by Django 5.2.17 on 2026-09-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=96, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("confirmed", "Confirmed")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AccessOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("view", "Page / endpoint"), ("role", "Role")],
                        max_length=8,
                    ),
                ),
                ("key", models.CharField(max_length=96)),
                ("value", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access.account",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "key"],
                "unique_together": {("kind", "key")},
            },
        ),
    ]
