# Generated by Django 5.2.17 on 2026-08-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_projecttask_sl_created_at_projecttask_sl_created_by_and_more"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_key", models.CharField(max_length=200, unique=True)),
                ("street", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=40)),
                ("state", models.CharField(blank=True, max_length=8)),
                ("zip", models.CharField(blank=True, max_length=12)),
                ("ok", models.BooleanField(default=False)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("census", "US Census Geocoder"),
                            ("nominatim", "Nominatim (OpenStreetMap)"),
                            ("manual", "Entered by hand"),
                        ],
                        max_length=12,
                    ),
                ),
                ("match_type", models.CharField(blank=True, max_length=24)),
                ("matched_address", models.CharField(blank=True, max_length=160)),
                ("precision", models.CharField(blank=True, max_length=12)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_customer_id", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("addr1", models.CharField(blank=True, max_length=64)),
                ("addr2", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=32)),
                ("state", models.CharField(blank=True, max_length=8)),
                ("zip", models.CharField(blank=True, max_length=12)),
                ("country", models.CharField(blank=True, max_length=8)),
                ("bill_addr1", models.CharField(blank=True, max_length=64)),
                ("bill_city", models.CharField(blank=True, max_length=32)),
                ("bill_state", models.CharField(blank=True, max_length=8)),
                ("bill_zip", models.CharField(blank=True, max_length=12)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.customer",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("site", "Sales-order ship-to"),
                            ("customer", "Customer address"),
                            ("city", "Customer city"),
                            ("manual", "Set by hand"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("exact", "Street-level, exact"),
                            ("approx", "Street-level, approximate"),
                            ("city", "City centroid"),
                        ],
                        max_length=12,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("site_name", models.CharField(blank=True, max_length=64)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "geocoded_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.geocodedaddress",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source"], name="geo_project_source_b9ac31_idx"
                    ),
                    models.Index(
                        fields=["lat", "lng"], name="geo_project_lat_19e4fe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectSiteAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_number_raw", models.CharField(max_length=32)),
                ("sl_customer_id", models.CharField(blank=True, max_length=15)),
                ("ship_to_id", models.CharField(blank=True, max_length=15)),
                ("orders", models.IntegerField(default=0)),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("site_name", models.CharField(blank=True, max_length=64)),
                ("addr1", models.CharField(blank=True, max_length=64)),
                ("addr2", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=32)),
                ("state", models.CharField(blank=True, max_length=8)),
                ("zip", models.CharField(blank=True, max_length=12)),
                ("country", models.CharField(blank=True, max_length=8)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_addresses",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project"], name="geo_project_project_7734dd_idx"
                    )
                ],
            },
        ),
    ]
