# Generated by Django 5.2.17 on 2026-09-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
        ("ingestion", "0001_initial"),
        ("sales", "0002_widen_cnet_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ship", "CNET ship-to"),
                            ("customer", "Customer address"),
                            ("city", "Customer city"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("exact", "Street-level, exact"),
                            ("approx", "Street-level, approximate"),
                            ("city", "City centroid"),
                        ],
                        max_length=12,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("site_name", models.CharField(blank=True, max_length=120)),
                ("address_key", models.CharField(blank=True, max_length=200)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="sales.cnetdocument",
                    ),
                ),
                (
                    "geocoded_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.geocodedaddress",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["address_key"], name="geo_salesor_address_294bbd_idx"
                    )
                ],
            },
        ),
    ]
